 // 1. Catálogos JSON completos proporcionados
        const dbDatos = {
            opcionesSelects: {
                jurisdiccion: [
                    { value: "CONSTITUCIONAL", label: "CONSTITUCIONAL" },
                    { value: "CONTENCIOSO ADMINISTRATIVO", label: "CONTENCIOSO ADMINISTRATIVO" },
                    { value: "DISCIPLINARIA", label: "DISCIPLINARIA" },
                    { value: "ORDINARIA", label: "ORDINARIA" }
                ],
                tipodespacho: [
                    { value: "ALTA CORTE", label: "ALTA CORTE" },
                    { value: "COMISIÓN SECCIONAL", label: "COMISIÓN SECCIONAL" },
                    { value: "JUZGADO ADMINISTRATIVO", label: "JUZGADO ADMINISTRATIVO" },
                    { value: "JUZGADO DE CIRCUITO", label: "JUZGADO DE CIRCUITO" },
                    { value: "JUZGADO MUNICIPAL", label: "JUZGADO MUNICIPAL" },
                    { value: "TRIBUNAL ADMINISTRATIVO", label: "TRIBUNAL ADMINISTRATIVO" },
                    { value: "TRIBUNAL SUPERIOR", label: "TRIBUNAL SUPERIOR" }
                ],
                deptomunicipio: [
                    { value: "ABEJORRAL", label: "ABEJORRAL" }, { value: "ABREGO", label: "ABREGO" }, { value: "ABRIAQUÍ", label: "ABRIAQUÍ" }, { value: "ACACÍAS", label: "ACACÍAS" }, { value: "ACANDÍ", label: "ACANDÍ" },
                    { value: "ACEVEDO", label: "ACEVEDO" }, { value: "ACHÍ", label: "ACHÍ" }, { value: "AGRADO", label: "AGRADO" }, { value: "AGUA DE DIOS", label: "AGUA DE DIOS" }, { value: "AGUACHICA", label: "AGUACHICA" },
                    { value: "AGUADA", label: "AGUADA" }, { value: "AGUADAS", label: "AGUADAS" }, { value: "AGUAZUL", label: "AGUAZUL" }, { value: "AGUSTÍN CODAZZI", label: "AGUSTÍN CODAZZI" }, { value: "AIPE", label: "AIPE" },
                    { value: "ALBÁN", label: "ALBÁN" }, { value: "ALBÁN SAN JOSÉ", label: "ALBÁN SAN JOSÉ" }, { value: "ALBANIA", label: "ALBANIA" }, { value: "ALCALÁ", label: "ALCALÁ" }, { value: "ALDANA", label: "ALDANA" },
                    { value: "ALEJANDRÍA", label: "ALEJANDRÍA" }, { value: "ALGARROBO", label: "ALGARROBO" }, { value: "ALGECIRAS", label: "ALGECIRAS" }, { value: "ALMAGUER", label: "ALMAGUER" }, { value: "ALMEIDA", label: "ALMEIDA" },
                    { value: "ALPUJARRA", label: "ALPUJARRA" }, { value: "ALTAMIRA", label: "ALTAMIRA" }, { value: "ALTO BAUDÓ", label: "ALTO BAUDÓ" }, { value: "ALTOS DEL ROSARIO", label: "ALTOS DEL ROSARIO" }, { value: "ALVARADO", label: "ALVARADO" },
                    { value: "AMAGÁ", label: "AMAGÁ" }, { value: "AMALFI", label: "AMALFI" }, { value: "AMBALEMA", label: "AMBALEMA" }, { value: "ANAPOIMA", label: "ANAPOIMA" }, { value: "ANCUYÁ", label: "ANCUYÁ" },
                    { value: "ANDALUCÍA", label: "ANDALUCÍA" }, { value: "ANDES", label: "ANDES" }, { value: "ANGELÓPOLIS", label: "ANGELÓPOLIS" }, { value: "ANGOSTURA", label: "ANGOSTURA" }, { value: "ANOLAIMA", label: "ANOLAIMA" },
                    { value: "ANORÍ", label: "ANORÍ" }, { value: "ANSERMA", label: "ANSERMA" }, { value: "ANSERMANUEVO", label: "ANSERMANUEVO" }, { value: "ANTIOQUIA", label: "ANTIOQUIA" }, { value: "ANZÁ", label: "ANZÁ" },
                    { value: "ANZOÁTEGUI", label: "ANZOÁTEGUI" }, { value: "APARTADÓ", label: "APARTADÓ" }, { value: "APÍA", label: "APÍA" }, { value: "APULO", label: "APULO" }, { value: "AQUITANIA", label: "AQUITANIA" },
                    { value: "ARACATACA", label: "ARACATACA" }, { value: "ARANZAZÚ", label: "ARANZAZÚ" }, { value: "ARATOCA", label: "ARATOCA" }, { value: "ARAUCA", label: "ARAUCA" }, { value: "ARAUQUITA", label: "ARAUQUITA" },
                    { value: "ARBELÁEZ", label: "ARBELÁEZ" }, { value: "ARBOLEDA", label: "ARBOLEDA" }, { value: "ARBOLEDAS", label: "ARBOLEDAS" }, { value: "ARBOLETES", label: "ARBOLETES" }, { value: "ARCABUCO", label: "ARCABUCO" },
                    { value: "ARENAL", label: "ARENAL" }, { value: "ARGELIA", label: "ARGELIA" }, { value: "ARIGUANÍ", label: "ARIGUANÍ" }, { value: "ARJONA", label: "ARJONA" }, { value: "ARMENIA", label: "ARMENIA" },
                    { value: "ARROYOHONDO", label: "ARROYOHONDO" }, { value: "ASTREA", label: "ASTREA" }, { value: "ATACO", label: "ATACO" }, { value: "ATRATO", label: "ATRATO" }, { value: "AYAPEL", label: "AYAPEL" },
                    { value: "BAGADÓ", label: "BAGADÓ" }, { value: "BAHÍA SOLANO", label: "BAHÍA SOLANO" }, { value: "BAJO BAUDÓ", label: "BAJO BAUDÓ" }, { value: "BALBOA", label: "BALBOA" }, { value: "BARANOA", label: "BARANOA" },
                    { value: "BARAYA", label: "BARAYA" }, { value: "BARBACOAS", label: "BARBACOAS" }, { value: "BARBOSA", label: "BARBOSA" }, { value: "BARICHARA", label: "BARICHARA" }, { value: "BARRANCA DE UPÍA", label: "BARRANCA DE UPÍA" },
                    { value: "BARRANCABERMEJA", label: "BARRANCABERMEJA" }, { value: "BARRANCAS", label: "BARRANCAS" }, { value: "BARRANCO DE LOBA", label: "BARRANCO DE LOBA" }, { value: "BARRANCO MINAS", label: "BARRANCO MINAS" }, { value: "BARRANQUILLA", label: "BARRANQUILLA" },
                    { value: "BECERRIL", label: "BECERRIL" }, { value: "BELALCAZAR", label: "BELALCAZAR" }, { value: "BELÉN", label: "BELÉN" }, { value: "BELÉN DE BAJIRÁ", label: "BELÉN DE BAJIRÁ" }, { value: "BELÉN DE LOS ANDAQUÍES", label: "BELÉN DE LOS ANDAQUÍES" },
                    { value: "BELÉN DE UMBRÍA", label: "BELÉN DE UMBRÍA" }, { value: "BELLO", label: "BELLO" }, { value: "BELMIRA", label: "BELMIRA" }, { value: "BELTRÁN", label: "BELTRÁN" }, { value: "BERBEO", label: "BERBEO" },
                    { value: "BETANIA", label: "BETANIA" }, { value: "BETÉITIVA", label: "BETÉITIVA" }, { value: "BETULIA", label: "BETULIA" }, { value: "BITUIMA", label: "BITUIMA" }, { value: "BOAVITA", label: "BOAVITA" },
                    { value: "BOCHALEMA", label: "BOCHALEMA" }, { value: "BOGOTÁ", label: "BOGOTÁ" }, { value: "BOJACÁ", label: "BOJACÁ" }, { value: "BOJAYÁ", label: "BOJAYÁ" }, { value: "BOLÍVAR", label: "BOLÍVAR" },
                    { value: "BOSCONIA", label: "BOSCONIA" }, { value: "BOYACÁ", label: "BOYACÁ" }, { value: "BRICEÑO", label: "BRICEÑO" }, { value: "BUCARAMANGA", label: "BUCARAMANGA" }, { value: "BUCARASICA", label: "BUCARASICA" },
                    { value: "BUENAVENTURA", label: "BUENAVENTURA" }, { value: "BUENAVISTA", label: "BUENAVISTA" }, { value: "BUENOS AIRES", label: "BUENOS AIRES" }, { value: "BUESACO", label: "BUESACO" }, { value: "BUGA", label: "BUGA" },
                    { value: "BUGALAGRANDE", label: "BUGALAGRANDE" }, { value: "BURITICÁ", label: "BURITICÁ" }, { value: "BUSBANZA", label: "BUSBANZA" }, { value: "CABRERA", label: "CABRERA" }, { value: "CABUYARO", label: "CABUYARO" },
                    { value: "CÁCERES", label: "CÁCERES" }, { value: "CACHIPAY", label: "CACHIPAY" }, { value: "CÁCHIRA", label: "CÁCHIRA" }, { value: "CÁCOTA", label: "CÁCOTA" }, { value: "CAICEDO", label: "CAICEDO" },
                    { value: "CAICEDONIA", label: "CAICEDONIA" }, { value: "CAIMITO", label: "CAIMITO" }, { value: "CAJAMARCA", label: "CAJAMARCA" }, { value: "CAJIBÍO", label: "CAJIBÍO" }, { value: "CAJICÁ", label: "CAJICÁ" },
                    { value: "CALAMAR", label: "CALAMAR" }, { value: "CALARCÁ", label: "CALARCÁ" }, { value: "CALDAS", label: "CALDAS" }, { value: "CALDONO", label: "CALDONO" }, { value: "CALI", label: "CALI" },
                    { value: "CALIFORNIA", label: "CALIFORNIA" }, { value: "CALIMA", label: "CALIMA" }, { value: "CALOTO", label: "CALOTO" }, { value: "CAMPAMENTO", label: "CAMPAMENTO" }, { value: "CAMPO DE LA CRUZ", label: "CAMPO DE LA CRUZ" },
                    { value: "CAMPOALEGRE", label: "CAMPOALEGRE" }, { value: "CAMPOHERMOSO", label: "CAMPOHERMOSO" }, { value: "CANALETE", label: "CANALETE" }, { value: "CANDELARIA", label: "CANDELARIA" }, { value: "CANTAGALLO", label: "CANTAGALLO" },
                    { value: "CANTÓN DE SAN PABLO", label: "CANTÓN DE SAN PABLO" }, { value: "CAÑASGORDAS", label: "CAÑASGORDAS" }, { value: "CAPARRAPÍ", label: "CAPARRAPÍ" }, { value: "CAPITANEJO", label: "CAPITANEJO" }, { value: "CÁQUEZA", label: "CÁQUEZA" },
                    { value: "CARACOLÍ", label: "CARACOLÍ" }, { value: "CARAMANTA", label: "CARAMANTA" }, { value: "CARCASÍ", label: "CARCASÍ" }, { value: "CAREPA", label: "CAREPA" }, { value: "CARMEN DE APICALÁ", label: "CARMEN DE APICALÁ" },
                    { value: "CARMEN DE BOLÍVAR", label: "CARMEN DE BOLÍVAR" }, { value: "CARMEN DE CARUPA", label: "CARMEN DE CARUPA" }, { value: "CARMEN DEL DARIÉN", label: "CARMEN DEL DARIÉN" }, { value: "CAROLINA", label: "CAROLINA" }, { value: "CARTAGENA", label: "CARTAGENA" },
                    { value: "CARTAGENA DEL CHAIRÁ", label: "CARTAGENA DEL CHAIRÁ" }, { value: "CARTAGO", label: "CARTAGO" }, { value: "CARURÚ", label: "CARURÚ" }, { value: "CASABIANCA", label: "CASABIANCA" }, { value: "CASTILLA LA NUEVA", label: "CASTILLA LA NUEVA" },
                    { value: "CAUCASIA", label: "CAUCASIA" }, { value: "CEPITÁ", label: "CEPITÁ" }, { value: "CERETÉ", label: "CERETÉ" }, { value: "CERINZA", label: "CERINZA" }, { value: "CERRITO", label: "CERRITO" },
                    { value: "CERRO DE SAN ANTONIO", label: "CERRO DE SAN ANTONIO" }, { value: "CERTEGUI", label: "CERTEGUI" }, { value: "CHACHAGÜÍ", label: "CHACHAGÜÍ" }, { value: "CHAGUANÍ", label: "CHAGUANÍ" }, { value: "CHALÁN", label: "CHALÁN" },
                    { value: "CHÁMEZA", label: "CHÁMEZA" }, { value: "CHAPARRAL", label: "CHAPARRAL" }, { value: "CHARALÁ", label: "CHARALÁ" }, { value: "CHARTA", label: "CHARTA" }, { value: "CHÍA", label: "CHÍA" },
                    { value: "CHIGORODÓ", label: "CHIGORODÓ" }, { value: "CHIMA", label: "CHIMA" }, { value: "CHIMICHAGUA", label: "CHIMICHAGUA" }, { value: "CHINÁCOTA", label: "CHINÁCOTA" }, { value: "CHINAVITA", label: "CHINAVITA" },
                    { value: "CHINCHINÁ", label: "CHINCHINÁ" }, { value: "CHINÚ", label: "CHINÚ" }, { value: "CHIPAQUE", label: "CHIPAQUE" }, { value: "CHIPATÁ", label: "CHIPATÁ" }, { value: "CHIQUINQUIRÁ", label: "CHIQUINQUIRÁ" },
                    { value: "CHÍQUIZA", label: "CHÍQUIZA" }, { value: "CHIRIGUANÁ", label: "CHIRIGUANÁ" }, { value: "CHISCAS", label: "CHISCAS" }, { value: "CHITA", label: "CHITA" }, { value: "CHITAGÁ", label: "CHITAGÁ" },
                    { value: "CHITARAQUE", label: "CHITARAQUE" }, { value: "CHIVATÁ", label: "CHIVATÁ" }, { value: "CHIVOLO", label: "CHIVOLO" }, { value: "CHIVOR", label: "CHIVOR" }, { value: "CHOACHÍ", label: "CHOACHÍ" },
                    { value: "CHOCONTÁ", label: "CHOCONTÁ" }, { value: "CICUCO", label: "CICUCO" }, { value: "CIÉNAGA", label: "CIÉNAGA" }, { value: "CIÉNAGA DE ORO", label: "CIÉNAGA DE ORO" }, { value: "CIÉNEGA", label: "CIÉNEGA" },
                    { value: "CIMITARRA", label: "CIMITARRA" }, { value: "CIRCASIA", label: "CIRCASIA" }, { value: "CISNEROS", label: "CISNEROS" }, { value: "CLEMENCIA", label: "CLEMENCIA" }, { value: "COCORNÁ", label: "COCORNÁ" },
                    { value: "COELLO", label: "COELLO" }, { value: "COGUA", label: "COGUA" }, { value: "COLOMBIA", label: "COLOMBIA" }, { value: "COLÓN", label: "COLÓN" }, { value: "COLOSÓ", label: "COLOSÓ" },
                    { value: "CÓMBITA", label: "CÓMBITA" }, { value: "CONCEPCIÓN", label: "CONCEPCIÓN" }, { value: "CONCORDIA", label: "CONCORDIA" }, { value: "CONDOTO", label: "CONDOTO" }, { value: "CONFINES", label: "CONFINES" },
                    { value: "CONSACÁ", label: "CONSACÁ" }, { value: "CONTADERO", label: "CONTADERO" }, { value: "CONTRATACIÓN", label: "CONTRATACIÓN" }, { value: "CONVENCIÓN", label: "CONVENCIÓN" }, { value: "COPACABANA", label: "COPACABANA" },
                    { value: "COPER", label: "COPER" }, { value: "CÓRDOBA", label: "CÓRDOBA" }, { value: "CORINTO", label: "CORINTO" }, { value: "COROMORO", label: "COROMORO" }, { value: "COROZAL", label: "COROZAL" },
                    { value: "CORRALES", label: "CORRALES" }, { value: "COTA", label: "COTA" }, { value: "COTORRA", label: "COTORRA" }, { value: "COVARACHÍA", label: "COVARACHÍA" }, { value: "COVEÑAS", label: "COVEÑAS" },
                    { value: "COYAIMA", label: "COYAIMA" }, { value: "CRAVO NORTE", label: "CRAVO NORTE" }, { value: "CUASPUD", label: "CUASPUD" }, { value: "CUBARÁ", label: "CUBARÁ" }, { value: "CUBARRAL", label: "CUBARRAL" },
                    { value: "CUCAITA", label: "CUCAITA" }, { value: "CUCUNUBÁ", label: "CUCUNUBÁ" }, { value: "CÚCUTA", label: "CÚCUTA" }, { value: "CUCUTILLA", label: "CUCUTILLA" }, { value: "CUÍTIVA", label: "CUÍTIVA" },
                    { value: "CUMARAL", label: "CUMARAL" }, { value: "CUMARIBO", label: "CUMARIBO" }, { value: "CUMBAL", label: "CUMBAL" }, { value: "CUMBITARA", label: "CUMBITARA" }, { value: "CUNDAY", label: "CUNDAY" },
                    { value: "CURILLO", label: "CURILLO" }, { value: "CURITÍ", label: "CURITÍ" }, { value: "CURUMANÍ", label: "CURUMANÍ" }, { value: "DABEIBA", label: "DABEIBA" }, { value: "DAGUA", label: "DAGUA" },
                    { value: "DIBULLA", label: "DIBULLA" }, { value: "DISTRACCIÓN", label: "DISTRACCIÓN" }, { value: "DOLORES", label: "DOLORES" }, { value: "DON MATÍAS", label: "DON MATÍAS" }, { value: "DOSQUEBRADAS", label: "DOSQUEBRADAS" },
                    { value: "DUITAMA", label: "DUITAMA" }, { value: "DURANIA", label: "DURANIA" }, { value: "EBÉJICO", label: "EBÉJICO" }, { value: "EL ÁGUILA", label: "EL ÁGUILA" }, { value: "EL BAGRE", label: "EL BAGRE" },
                    { value: "EL BANCO", label: "EL BANCO" }, { value: "EL CAIRO", label: "EL CAIRO" }, { value: "EL CALVARIO", label: "EL CALVARIO" }, { value: "EL CARMEN", label: "EL CARMEN" }, { value: "EL CARMEN DE ATRATO", label: "EL CARMEN DE ATRATO" },
                    { value: "EL CARMEN DE CHUCURÍ", label: "EL CARMEN DE CHUCURÍ" }, { value: "EL CARMEN DE VIBORAL", label: "EL CARMEN DE VIBORAL" }, { value: "EL CASTILLO", label: "EL CASTILLO" }, { value: "EL CERRITO", label: "EL CERRITO" }, { value: "EL CHARCO", label: "EL CHARCO" },
                    { value: "EL COCUY", label: "EL COCUY" }, { value: "EL COLEGIO", label: "EL COLEGIO" }, { value: "EL COPEY", label: "EL COPEY" }, { value: "EL DONCELLO", label: "EL DONCELLO" }, { value: "EL DORADO", label: "EL DORADO" },
                    { value: "EL DOVIO", label: "EL DOVIO" }, { value: "EL ESPINO", label: "EL ESPINO" }, { value: "EL GUACAMAYO", label: "EL GUACAMAYO" }, { value: "EL GUAMO", label: "EL GUAMO" }, { value: "EL MOLINO", label: "EL MOLINO" },
                    { value: "EL PASO", label: "EL PASO" }, { value: "EL PAUJIL", label: "EL PAUJIL" }, { value: "EL PEÑOL", label: "EL PEÑOL" }, { value: "EL PEÑÓN", label: "EL PEÑÓN" }, { value: "EL PIÑÓN", label: "EL PIÑÓN" },
                    { value: "EL PLAYÓN", label: "EL PLAYÓN" }, { value: "EL RETÉN", label: "EL RETÉN" }, { value: "EL RETIRO", label: "EL RETIRO" }, { value: "EL RETORNO", label: "EL RETORNO" }, { value: "EL ROBLE", label: "EL ROBLE" },
                    { value: "EL ROSAL", label: "EL ROSAL" }, { value: "EL ROSARIO", label: "EL ROSARIO" }, { value: "EL SANTUARIO", label: "EL SANTUARIO" }, { value: "EL TABLÓN DE GÓMEZ", label: "EL TABLÓN DE GÓMEZ" }, { value: "EL TAMBO", label: "EL TAMBO" },
                    { value: "EL TARRA", label: "EL TARRA" }, { value: "EL ZULIA", label: "EL ZULIA" }, { value: "ELÍAS", label: "ELÍAS" }, { value: "ENCINO", label: "ENCINO" }, { value: "ENCISO", label: "ENCISO" },
                    { value: "ENTRERRÍOS", label: "ENTRERRÍOS" }, { value: "ENVIGADO", label: "ENVIGADO" }, { value: "ESPINAL", label: "ESPINAL" }, { value: "FACATATIVÁ", label: "FACATATIVÁ" }, { value: "FALAN", label: "FALAN" },
                    { value: "FILADELFIA", label: "FILADELFIA" }, { value: "FILANDIA", label: "FILANDIA" }, { value: "FIRAVITOBA", label: "FIRAVITOBA" }, { value: "FLANDES", label: "FLANDES" }, { value: "FLORENCIA", label: "FLORENCIA" },
                    { value: "FLORESTA", label: "FLORESTA" }, { value: "FLORIÁN", label: "FLORIÁN" }, { value: "FLORIDA", label: "FLORIDA" }, { value: "FLORIDABLANCA", label: "FLORIDABLANCA" }, { value: "FÓMEQUE", label: "FÓMEQUE" },
                    { value: "FONSECA", label: "FONSECA" }, { value: "FORTUL", label: "FORTUL" }, { value: "FOSCA", label: "FOSCA" }, { value: "FRANCISCO PIZARRO", label: "FRANCISCO PIZARRO" }, { value: "FREDONIA", label: "FREDONIA" },
                    { value: "FRESNO", label: "FRESNO" }, { value: "FRONTINO", label: "FRONTINO" }, { value: "FUENTE DE ORO", label: "FUENTE DE ORO" }, { value: "FUNDACIÓN", label: "FUNDACIÓN" }, { value: "FUNES", label: "FUNES" },
                    { value: "FUNZA", label: "FUNZA" }, { value: "FÚQUENE", label: "FÚQUENE" }, { value: "FUSAGASUGÁ", label: "FUSAGASUGÁ" }, { value: "GACHALÁ", label: "GACHALÁ" }, { value: "GACHANCIPÁ", label: "GACHANCIPÁ" },
                    { value: "GACHANTIVÁ", label: "GACHANTIVÁ" }, { value: "GACHETÁ", label: "GACHETÁ" }, { value: "GALÁN", label: "GALÁN" }, { value: "GALAPA", label: "GALAPA" }, { value: "GALERAS", label: "GALERAS" },
                    { value: "GAMA", label: "GAMA" }, { value: "GAMARRA", label: "GAMARRA" }, { value: "GÁMBITA", label: "GÁMBITA" }, { value: "GÁMEZA", label: "GÁMEZA" }, { value: "GARAGOA", label: "GARAGOA" },
                    { value: "GARZÓN", label: "GARZÓN" }, { value: "GÉNOVA", label: "GÉNOVA" }, { value: "GIGANTE", label: "GIGANTE" }, { value: "GINEBRA", label: "GINEBRA" }, { value: "GIRALDO", label: "GIRALDO" },
                    { value: "GIRARDOT", label: "GIRARDOT" }, { value: "GIRARDOTA", label: "GIRARDOTA" }, { value: "GIRÓN", label: "GIRÓN" }, { value: "GÓMEZ PLATA", label: "GÓMEZ PLATA" }, { value: "GONZÁLEZ", label: "GONZÁLEZ" },
                    { value: "GRAMALOTE", label: "GRAMALOTE" }, { value: "GRANADA", label: "GRANADA" }, { value: "GUACA", label: "GUACA" }, { value: "GUACAMAYAS", label: "GUACAMAYAS" }, { value: "GUACARÍ", label: "GUACARÍ" },
                    { value: "GUACHENÉ", label: "GUACHENÉ" }, { value: "GUACHETÁ", label: "GUACHETÁ" }, { value: "GUACHUCAL", label: "GUACHUCAL" }, { value: "GUADALUPE", label: "GUADALUPE" }, { value: "GUADUAS", label: "GUADUAS" },
                    { value: "GUAITARILLA", label: "GUAITARILLA" }, { value: "GUALMATÁN", label: "GUALMATÁN" }, { value: "GUAMAL", label: "GUAMAL" }, { value: "GUAMO", label: "GUAMO" }, { value: "GUAPÍ", label: "GUAPÍ" },
                    { value: "GUAPOTÁ", label: "GUAPOTÁ" }, { value: "GUARANDÁ", label: "GUARANDÁ" }, { value: "GUARNE", label: "GUARNE" }, { value: "GUASCA", label: "GUASCA" }, { value: "GUATAPÉ", label: "GUATAPÉ" },
                    { value: "GUATAQUÍ", label: "GUATAQUÍ" }, { value: "GUATAVITA", label: "GUATAVITA" }, { value: "GUATEQUE", label: "GUATEQUE" }, { value: "GUÁTICA", label: "GUÁTICA" }, { value: "GUAVATÁ", label: "GUAVATÁ" },
                    { value: "GUAYABAL (ARMERO)", label: "GUAYABAL (ARMERO)" }, { value: "GUAYABAL DE SÍQUIMA", label: "GUAYABAL DE SÍQUIMA" }, { value: "GUAYABETAL", label: "GUAYABETAL" }, { value: "GUAYATÁ", label: "GUAYATÁ" }, { value: "GÜEPSA", label: "GÜEPSA" },
                    { value: "GÜICÁN", label: "GÜICÁN" }, { value: "GUTIÉRREZ", label: "GUTIÉRREZ" }, { value: "HACARÍ", label: "HACARÍ" }, { value: "HATILLO DE LOBA", label: "HATILLO DE LOBA" }, { value: "HATO", label: "HATO" },
                    { value: "HATO COROZAL", label: "HATO COROZAL" }, { value: "HATO NUEVO", label: "HATO NUEVO" }, { value: "HELICONIA", label: "HELICONIA" }, { value: "HERRÁN", label: "HERRÁN" }, { value: "HERVEO", label: "HERVEO" },
                    { value: "HISPANIA", label: "HISPANIA" }, { value: "HOBO", label: "HOBO" }, { value: "HONDA", label: "HONDA" }, { value: "IBAGUÉ", label: "IBAGUÉ" }, { value: "ICONONZO", label: "ICONONZO" },
                    { value: "ILES", label: "ILES" }, { value: "IMUES", label: "IMUES" }, { value: "INÍRIDA", label: "INÍRIDA" }, { value: "INZÁ", label: "INZÁ" }, { value: "IPIALES", label: "IPIALES" },
                    { value: "IQUIRA", label: "IQUIRA" }, { value: "ISNOS", label: "ISNOS" }, { value: "ISTMINA", label: "ISTMINA" }, { value: "ITAGÜÍ", label: "ITAGÜÍ" }, { value: "ITUANGO", label: "ITUANGO" },
                    { value: "IZA", label: "IZA" }, { value: "JAMBALÓ", label: "JAMBALÓ" }, { value: "JAMUNDÍ", label: "JAMUNDÍ" }, { value: "JARDÍN", label: "JARDÍN" }, { value: "JENESANO", label: "JENESANO" },
                    { value: "JERICÓ", label: "JERICÓ" }, { value: "JERUSALÉN", label: "JERUSALÉN" }, { value: "JESÚS MARÍA", label: "JESÚS MARÍA" }, { value: "JORDÁN SUBE", label: "JORDÁN SUBE" }, { value: "JUAN DE ACOSTA", label: "JUAN DE ACOSTA" },
                    { value: "JUNÍN", label: "JUNÍN" }, { value: "JURADÓ", label: "JURADÓ" }, { value: "LA APARTADA", label: "LA APARTADA" }, { value: "LA ARGENTINA", label: "LA ARGENTINA" }, { value: "LA BELLEZA", label: "LA BELLEZA" },
                    { value: "LA CALERA", label: "LA CALERA" }, { value: "LA CAPILLA", label: "LA CAPILLA" }, { value: "LA CEJA", label: "LA CEJA" }, { value: "LA CELIA", label: "LA CELIA" }, { value: "LA CRUZ", label: "LA CRUZ" },
                    { value: "LA CUMBRE", label: "LA CUMBRE" }, { value: "LA DORADA", label: "LA DORADA" }, { value: "LA ESPERANZA", label: "LA ESPERANZA" }, { value: "LA ESTRELLA", label: "LA ESTRELLA" }, { value: "LA FLORIDA", label: "LA FLORIDA" },
                    { value: "LA GLORIA", label: "LA GLORIA" }, { value: "LA JAGUA DE IBIRICO", label: "LA JAGUA DE IBIRICO" }, { value: "LA JAGUA DEL PILAR", label: "LA JAGUA DEL PILAR" }, { value: "LA LLANADA", label: "LA LLANADA" }, { value: "LA MACARENA", label: "LA MACARENA" },
                    { value: "LA MERCED", label: "LA MERCED" }, { value: "LA MESA", label: "LA MESA" }, { value: "LA MONTAÑITA", label: "LA MONTAÑITA" }, { value: "LA PALMA", label: "LA PALMA" }, { value: "LA PAZ", label: "LA PAZ" },
                    { value: "LA PAZ (ROBLES)", label: "LA PAZ (ROBLES)" }, { value: "LA PEÑA", label: "LA PEÑA" }, { value: "LA PINTADA", label: "LA PINTADA" }, { value: "LA PLATA", label: "LA PLATA" }, { value: "LA PLAYA", label: "LA PLAYA" },
                    { value: "LA PRIMAVERA", label: "LA PRIMAVERA" }, { value: "LA SALINA", label: "LA SALINA" }, { value: "LA SIERRA", label: "LA SIERRA" }, { value: "LA TEBAIDA", label: "LA TEBAIDA" }, { value: "LA TOLA", label: "LA TOLA" },
                    { value: "LA UNIÓN", label: "LA UNIÓN" }, { value: "LA URIBE", label: "LA URIBE" }, { value: "LA UVITA", label: "LA UVITA" }, { value: "LA VEGA", label: "LA VEGA" }, { value: "LA VICTORIA", label: "LA VICTORIA" },
                    { value: "LA VIRGINIA", label: "LA VIRGINIA" }, { value: "LABATECA", label: "LABATECA" }, { value: "LABRANZAGRANDE", label: "LABRANZAGRANDE" }, { value: "LANDÁZURI", label: "LANDÁZURI" }, { value: "LEBRIJA", label: "LEBRIJA" },
                    { value: "LEJANÍAS", label: "LEJANÍAS" }, { value: "LENGUAZAQUE", label: "LENGUAZAQUE" }, { value: "LÉRIDA", label: "LÉRIDA" }, { value: "LETICIA", label: "LETICIA" }, { value: "LEYVA", label: "LEYVA" },
                    { value: "LÍBANO", label: "LÍBANO" }, { value: "LIBORINA", label: "LIBORINA" }, { value: "LINARES", label: "LINARES" }, { value: "LITORAL DE SAN JUAN", label: "LITORAL DE SAN JUAN" }, { value: "LLORÓ", label: "LLORÓ" },
                    { value: "LÓPEZ DE MICAY", label: "LÓPEZ DE MICAY" }, { value: "LORICA", label: "LORICA" }, { value: "LOS ANDES", label: "LOS ANDES" }, { value: "LOS CÓRDOBAS", label: "LOS CÓRDOBAS" }, { value: "LOS PALMITOS", label: "LOS PALMITOS" },
                    { value: "LOS PATIOS", label: "LOS PATIOS" }, { value: "LOS SANTOS", label: "LOS SANTOS" }, { value: "LOURDES", label: "LOURDES" }, { value: "LURUACO", label: "LURUACO" }, { value: "MACANAL", label: "MACANAL" },
                    { value: "MACARAVITA", label: "MACARAVITA" }, { value: "MACEO", label: "MACEO" }, { value: "MACHETÁ", label: "MACHETÁ" }, { value: "MADRID", label: "MADRID" }, { value: "MAGANGUÉ", label: "MAGANGUÉ" },
                    { value: "MAGÜI-PAYÁN", label: "MAGÜI-PAYÁN" }, { value: "MAHATES", label: "MAHATES" }, { value: "MAICAO", label: "MAICAO" }, { value: "MAJAGUAL", label: "MAJAGUAL" }, { value: "MÁLAGA", label: "MÁLAGA" },
                    { value: "MALAMBO", label: "MALAMBO" }, { value: "MALLAMA", label: "MALLAMA" }, { value: "MANATÍ", label: "MANATÍ" }, { value: "MANAURE", label: "MANAURE" }, { value: "MANÍ", label: "MANÍ" },
                    { value: "MANIZALES", label: "MANIZALES" }, { value: "MANTA", label: "MANTA" }, { value: "MANZANARES", label: "MANZANARES" }, { value: "MAPIRIPÁN", label: "MAPIRIPÁN" }, { value: "MARGARITA", label: "MARGARITA" },
                    { value: "MARÍA LA BAJA", label: "MARÍA LA BAJA" }, { value: "MARINILLA", label: "MARINILLA" }, { value: "MARIPÍ", label: "MARIPÍ" }, { value: "MARIQUITA", label: "MARIQUITA" }, { value: "MARMATO", label: "MARMATO" },
                    { value: "MARQUETALIA", label: "MARQUETALIA" }, { value: "MARSELLA", label: "MARSELLA" }, { value: "MARULANDA", label: "MARULANDA" }, { value: "MATANZA", label: "MATANZA" }, { value: "MEDELLÍN", label: "MEDELLÍN" },
                    { value: "MEDINA", label: "MEDINA" }, { value: "MEDIO ATRATO", label: "MEDIO ATRATO" }, { value: "MEDIO BAUDÓ", label: "MEDIO BAUDÓ" }, { value: "MEDIO SAN JUAN", label: "MEDIO SAN JUAN" }, { value: "MELGAR", label: "MELGAR" },
                    { value: "MERCADERES", label: "MERCADERES" }, { value: "MESETAS", label: "MESETAS" }, { value: "MILÁN", label: "MILÁN" }, { value: "MIRAFLORES", label: "MIRAFLORES" }, { value: "MIRANDA", label: "MIRANDA" },
                    { value: "MISTRATÓ", label: "MISTRATÓ" }, { value: "MITÚ", label: "MITÚ" }, { value: "MOCOA", label: "MOCOA" }, { value: "MOGOTES", label: "MOGOTES" }, { value: "MOLAGAVITA", label: "MOLAGAVITA" },
                    { value: "MOMIL", label: "MOMIL" }, { value: "MOMPÓS", label: "MOMPÓS" }, { value: "MONGUA", label: "MONGUA" }, { value: "MONGUÍ", label: "MONGUÍ" }, { value: "MONIQUIRÁ", label: "MONIQUIRÁ" },
                    { value: "MONTEBELLO", label: "MONTEBELLO" }, { value: "MONTECRISTO", label: "MONTECRISTO" }, { value: "MONTELÍBANO", label: "MONTELÍBANO" }, { value: "MONTENEGRO", label: "MONTENEGRO" }, { value: "MONTERÍA", label: "MONTERÍA" },
                    { value: "MONTERREY", label: "MONTERREY" }, { value: "MOÑITOS", label: "MOÑITOS" }, { value: "MORALES", label: "MORALES" }, { value: "MORELIA", label: "MORELIA" }, { value: "MORROA", label: "MORROA" },
                    { value: "MOSQUERA", label: "MOSQUERA" }, { value: "MOTAVITA", label: "MOTAVITA" }, { value: "MURILLO", label: "MURILLO" }, { value: "MURINDÓ", label: "MURINDÓ" }, { value: "MUTATÁ", label: "MUTATÁ" },
                    { value: "MUTISCUA", label: "MUTISCUA" }, { value: "MUZO", label: "MUZO" }, { value: "NARIÑO", label: "NARIÑO" }, { value: "NÁTAGA", label: "NÁTAGA" }, { value: "NATAGAIMA", label: "NATAGAIMA" },
                    { value: "NECHÍ", label: "NECHÍ" }, { value: "NECOCLÍ", label: "NECOCLÍ" }, { value: "NEIRA", label: "NEIRA" }, { value: "NEIVA", label: "NEIVA" }, { value: "NEMOCÓN", label: "NEMOCÓN" },
                    { value: "NILO", label: "NILO" }, { value: "NIMAIMA", label: "NIMAIMA" }, { value: "NOBSA", label: "NOBSA" }, { value: "NOCAIMA", label: "NOCAIMA" }, { value: "NORCASIA", label: "NORCASIA" },
                    { value: "NOROSÍ", label: "NOROSÍ" }, { value: "NÓVITA", label: "NÓVITA" }, { value: "NUEVA GRANADA", label: "NUEVA GRANADA" }, { value: "NUEVO COLÓN", label: "NUEVO COLÓN" }, { value: "NUNCHÍA", label: "NUNCHÍA" },
                    { value: "NUQUÍ", label: "NUQUÍ" }, { value: "OBANDO", label: "OBANDO" }, { value: "OCAMONTE", label: "OCAMONTE" }, { value: "OCAÑA", label: "OCAÑA" }, { value: "OIBA", label: "OIBA" },
                    { value: "OICATÁ", label: "OICATÁ" }, { value: "OLAYA", label: "OLAYA" }, { value: "OLAYA HERRERA", label: "OLAYA HERRERA" }, { value: "ONZAGA", label: "ONZAGA" }, { value: "OPORAPA", label: "OPORAPA" },
                    { value: "ORITO", label: "ORITO" }, { value: "OROCUÉ", label: "OROCUÉ" }, { value: "ORTEGA", label: "ORTEGA" }, { value: "OSPINA", label: "OSPINA" }, { value: "OTANCHE", label: "OTANCHE" },
                    { value: "OVEJAS", label: "OVEJAS" }, { value: "PACHAVITA", label: "PACHAVITA" }, { value: "PACHO", label: "PACHO" }, { value: "PÁCORA", label: "PÁCORA" }, { value: "PADILLA", label: "PADILLA" },
                    { value: "PÁEZ", label: "PÁEZ" }, { value: "PAEZ - BELALCÁZAR", label: "PAEZ - BELALCÁZAR" }, { value: "PAICOL", label: "PAICOL" }, { value: "PAILITAS", label: "PAILITAS" }, { value: "PAIME", label: "PAIME" },
                    { value: "PAIPA", label: "PAIPA" }, { value: "PAJARITO", label: "PAJARITO" }, { value: "PALERMO", label: "PALERMO" }, { value: "PALESTINA", label: "PALESTINA" }, { value: "PALMAR", label: "PALMAR" },
                    { value: "PALMAR DE VARELA", label: "PALMAR DE VARELA" }, { value: "PALMAS DEL SOCORRO", label: "PALMAS DEL SOCORRO" }, { value: "PALMIRA", label: "PALMIRA" }, { value: "PALMITO", label: "PALMITO" }, { value: "PALOCABILDO", label: "PALOCABILDO" },
                    { value: "PAMPLONA", label: "PAMPLONA" }, { value: "PAMPLONITA", label: "PAMPLONITA" }, { value: "PANDI", label: "PANDI" }, { value: "PANQUEBA", label: "PANQUEBA" }, { value: "PÁRAMO", label: "PÁRAMO" },
                    { value: "PARATEBUENO", label: "PARATEBUENO" }, { value: "PASCA", label: "PASCA" }, { value: "PASTO", label: "PASTO" }, { value: "PATÍA-EL BORDO", label: "PATÍA-EL BORDO" }, { value: "PAUNA", label: "PAUNA" },
                    { value: "PAYA", label: "PAYA" }, { value: "PAZ DE ARIPORO", label: "PAZ DE ARIPORO" }, { value: "PAZ DE RÍO", label: "PAZ DE RÍO" }, { value: "PEDRAZA", label: "PEDRAZA" }, { value: "PELAYA", label: "PELAYA" },
                    { value: "PENSILVANIA", label: "PENSILVANIA" }, { value: "PEQUÉ", label: "PEQUÉ" }, { value: "PEREIRA", label: "PEREIRA" }, { value: "PESCA", label: "PESCA" }, { value: "PIAMONTE", label: "PIAMONTE" },
                    { value: "PIEDECUESTA", label: "PIEDECUESTA" }, { value: "PIEDRAS", label: "PIEDRAS" }, { value: "PIENDAMÓ", label: "PIENDAMÓ" }, { value: "PIJAO", label: "PIJAO" }, { value: "PIJIÑO DEL CARMEN", label: "PIJIÑO DEL CARMEN" },
                    { value: "PINCHOTE", label: "PINCHOTE" }, { value: "PINILLOS", label: "PINILLOS" }, { value: "PIOJÓ", label: "PIOJÓ" }, { value: "PISBA", label: "PISBA" }, { value: "PITAL", label: "PITAL" },
                    { value: "PITALITO", label: "PITALITO" }, { value: "PIVIJAY", label: "PIVIJAY" }, { value: "PLANADAS", label: "PLANADAS" }, { value: "PLANETA RICA", label: "PLANETA RICA" }, { value: "PLATO", label: "PLATO" },
                    { value: "POLICARPA", label: "POLICARPA" }, { value: "POLO NUEVO", label: "POLO NUEVO" }, { value: "PONEDERA", label: "PONEDERA" }, { value: "POPAYÁN", label: "POPAYÁN" }, { value: "PORE", label: "PORE" },
                    { value: "POTOSÍ", label: "POTOSÍ" }, { value: "PRADERA", label: "PRADERA" }, { value: "PRADO", label: "PRADO" }, { value: "PROVIDENCIA", label: "PROVIDENCIA" }, { value: "PUEBLO BELLO", label: "PUEBLO BELLO" },
                    { value: "PUEBLO NUEVO", label: "PUEBLO NUEVO" }, { value: "PUEBLO RICO", label: "PUEBLO RICO" }, { value: "PUEBLO VIEJO", label: "PUEBLO VIEJO" }, { value: "PUENTE NACIONAL", label: "PUENTE NACIONAL" }, { value: "PUERRES", label: "PUERRES" },
                    { value: "PUERTO ASÍS", label: "PUERTO ASÍS" }, { value: "PUERTO BERRÍO", label: "PUERTO BERRÍO" }, { value: "PUERTO BOYACÁ", label: "PUERTO BOYACÁ" }, { value: "PUERTO CAICEDO", label: "PUERTO CAICEDO" }, { value: "PUERTO CARREÑO", label: "PUERTO CARREÑO" },
                    { value: "PUERTO COLOMBIA", label: "PUERTO COLOMBIA" }, { value: "PUERTO CONCORDIA", label: "PUERTO CONCORDIA" }, { value: "PUERTO ESCONDIDO", label: "PUERTO ESCONDIDO" }, { value: "PUERTO GAITÁN", label: "PUERTO GAITÁN" }, { value: "PUERTO GUZMÁN", label: "PUERTO GUZMÁN" },
                    { value: "PUERTO LEGUÍZAMO", label: "PUERTO LEGUÍZAMO" }, { value: "PUERTO LIBERTADOR", label: "PUERTO LIBERTADOR" }, { value: "PUERTO LLERAS", label: "PUERTO LLERAS" }, { value: "PUERTO LÓPEZ", label: "PUERTO LÓPEZ" }, { value: "PUERTO NARE", label: "PUERTO NARE" },
                    { value: "PUERTO NARIÑO", label: "PUERTO NARIÑO" }, { value: "PUERTO PARRA", label: "PUERTO PARRA" }, { value: "PUERTO RICO", label: "PUERTO RICO" }, { value: "PUERTO RONDÓN", label: "PUERTO RONDÓN" }, { value: "PUERTO SALGAR", label: "PUERTO SALGAR" },
                    { value: "PUERTO SANTANDER", label: "PUERTO SANTANDER" }, { value: "PUERTO TEJADA", label: "PUERTO TEJADA" }, { value: "PUERTO TRIUNFO", label: "PUERTO TRIUNFO" }, { value: "PUERTO WILCHES", label: "PUERTO WILCHES" }, { value: "PULÍ", label: "PULÍ" },
                    { value: "PUPIALES", label: "PUPIALES" }, { value: "PURACÉ-COCONUCO", label: "PURACÉ-COCONUCO" }, { value: "PURIFICACIÓN", label: "PURIFICACIÓN" }, { value: "PURÍSIMA", label: "PURÍSIMA" }, { value: "QUEBRADANEGRA", label: "QUEBRADANEGRA" },
                    { value: "QUETAME", label: "QUETAME" }, { value: "QUIBDÓ", label: "QUIBDÓ" }, { value: "QUIMBAYA", label: "QUIMBAYA" }, { value: "QUINCHÍA", label: "QUINCHÍA" }, { value: "QUÍPAMA", label: "QUÍPAMA" },
                    { value: "QUIPILE", label: "QUIPILE" }, { value: "RAGONVALIA", label: "RAGONVALIA" }, { value: "RAMIRIQUÍ", label: "RAMIRIQUÍ" }, { value: "RÁQUIRA", label: "RÁQUIRA" }, { value: "RECETOR", label: "RECETOR" },
                    { value: "REGIDOR", label: "REGIDOR" }, { value: "REMEDIOS", label: "REMEDIOS" }, { value: "REMOLINO", label: "REMOLINO" }, { value: "REPELÓN", label: "REPELÓN" }, { value: "RESTREPO", label: "RESTREPO" },
                    { value: "RICAURTE", label: "RICAURTE" }, { value: "RÍO DE ORO", label: "RÍO DE ORO" }, { value: "RÍO IRÓ", label: "RÍO IRÓ" }, { value: "RÍO QUITO", label: "RÍO QUITO" }, { value: "RIOBLANCO", label: "RIOBLANCO" },
                    { value: "RIOFRÍO", label: "RIOFRÍO" }, { value: "RIOHACHA", label: "RIOHACHA" }, { value: "RIONEGRO", label: "RIONEGRO" }, { value: "RIOSUCIO", label: "RIOSUCIO" }, { value: "RIOVIEJO", label: "RIOVIEJO" },
                    { value: "RISARALDA", label: "RISARALDA" }, { value: "RIVERA", label: "RIVERA" }, { value: "ROBERTO PAYÁN", label: "ROBERTO PAYÁN" }, { value: "ROLDANILLO", label: "ROLDANILLO" }, { value: "RONCESVALLES", label: "RONCESVALLES" },
                    { value: "RONDÓN", label: "RONDÓN" }, { value: "ROSAS", label: "ROSAS" }, { value: "ROVIRA", label: "ROVIRA" }, { value: "SABANA DE TORRES", label: "SABANA DE TORRES" }, { value: "SABANAGRANDE", label: "SABANAGRANDE" },
                    { value: "SABANALARGA", label: "SABANALARGA" }, { value: "SABANAS DE SAN ÁNGEL", label: "SABANAS DE SAN ÁNGEL" }, { value: "SABANETA", label: "SABANETA" }, { value: "SABOYÁ", label: "SABOYÁ" }, { value: "SÁCAMA", label: "SÁCAMA" },
                    { value: "SÁCHICA", label: "SÁCHICA" }, { value: "SAHAGÚN", label: "SAHAGÚN" }, { value: "SALADOBLANCO", label: "SALADOBLANCO" }, { value: "SALAMINA", label: "SALAMINA" }, { value: "SALAZAR", label: "SALAZAR" },
                    { value: "SALDAÑA", label: "SALDAÑA" }, { value: "SALENTO", label: "SALENTO" }, { value: "SALGAR", label: "SALGAR" }, { value: "SAMACÁ", label: "SAMACÁ" }, { value: "SAMANÁ", label: "SAMANÁ" },
                    { value: "SAMANIEGO", label: "SAMANIEGO" }, { value: "SAMPUÉS", label: "SAMPUÉS" }, { value: "SAN AGUSTÍN", label: "SAN AGUSTÍN" }, { value: "SAN ALBERTO", label: "SAN ALBERTO" }, { value: "SAN ANDRÉS", label: "SAN ANDRÉS" },
                    { value: "SAN ANDRÉS  DE SOTAVENTO", label: "SAN ANDRÉS  DE SOTAVENTO" }, { value: "SAN ANDRÉS DE BUGA", label: "SAN ANDRÉS DE BUGA" }, { value: "SAN ANDRÉS DE CUERQUÍA", label: "SAN ANDRÉS DE CUERQUÍA" }, { value: "SAN ANTERO", label: "SAN ANTERO" }, { value: "SAN ANTONIO", label: "SAN ANTONIO" },
                    { value: "SAN ANTONIO DEL TEQUENDAMA", label: "SAN ANTONIO DEL TEQUENDAMA" }, { value: "SAN BENITO", label: "SAN BENITO" }, { value: "SAN BENITO ABAD", label: "SAN BENITO ABAD" }, { value: "SAN BERNARDO", label: "SAN BERNARDO" }, { value: "SAN BERNARDO DEL VIENTO", label: "SAN BERNARDO DEL VIENTO" },
                    { value: "SAN CALIXTO", label: "SAN CALIXTO" }, { value: "SAN CARLOS", label: "SAN CARLOS" }, { value: "SAN CARLOS DE GUAROA", label: "SAN CARLOS DE GUAROA" }, { value: "SAN CAYETANO", label: "SAN CAYETANO" }, { value: "SAN CRISTOBAL", label: "SAN CRISTOBAL" },
                    { value: "SAN DIEGO", label: "SAN DIEGO" }, { value: "SAN EDUARDO", label: "SAN EDUARDO" }, { value: "SAN ESTANISLAO", label: "SAN ESTANISLAO" }, { value: "SAN FERNANDO", label: "SAN FERNANDO" }, { value: "SAN FRANCISCO", label: "SAN FRANCISCO" },
                    { value: "SAN GIL", label: "SAN GIL" }, { value: "SAN JACINTO", label: "SAN JACINTO" }, { value: "SAN JACINTO DEL CAUCA", label: "SAN JACINTO DEL CAUCA" }, { value: "SAN JERÓNIMO", label: "SAN JERÓNIMO" }, { value: "SAN JOAQUÍN", label: "SAN JOAQUÍN" },
                    { value: "SAN JOSÉ", label: "SAN JOSÉ" }, { value: "SAN JOSÉ DE FRAGUA", label: "SAN JOSÉ DE FRAGUA" }, { value: "SAN JOSÉ DE LA MONTAÑA", label: "SAN JOSÉ DE LA MONTAÑA" }, { value: "SAN JOSÉ DE MIRANDA", label: "SAN JOSÉ DE MIRANDA" }, { value: "SAN JOSÉ DE PARE", label: "SAN JOSÉ DE PARE" },
                    { value: "SAN JOSÉ DE URE", label: "SAN JOSÉ DE URE" }, { value: "SAN JOSÉ DEL GUAVIARE", label: "SAN JOSÉ DEL GUAVIARE" }, { value: "SAN JOSÉ DEL PALMAR", label: "SAN JOSÉ DEL PALMAR" }, { value: "SAN JUAN BETULIA", label: "SAN JUAN BETULIA" }, { value: "SAN JUAN DE ARAMA", label: "SAN JUAN DE ARAMA" },
                    { value: "SAN JUAN DE RIOSECO", label: "SAN JUAN DE RIOSECO" }, { value: "SAN JUAN DE URABÁ", label: "SAN JUAN DE URABÁ" }, { value: "SAN JUAN DEL CESAR", label: "SAN JUAN DEL CESAR" }, { value: "SAN JUAN NEPOMUCENO", label: "SAN JUAN NEPOMUCENO" }, { value: "SAN JUANITO", label: "SAN JUANITO" },
                    { value: "SAN LORENZO", label: "SAN LORENZO" }, { value: "SAN LUIS", label: "SAN LUIS" }, { value: "SAN LUIS DE GACENO", label: "SAN LUIS DE GACENO" }, { value: "SAN LUIS DE PALENQUE", label: "SAN LUIS DE PALENQUE" }, { value: "SAN MARCOS", label: "SAN MARCOS" },
                    { value: "SAN MARTÍN", label: "SAN MARTÍN" }, { value: "SAN MARTÍN DE LOBA", label: "SAN MARTÍN DE LOBA" }, { value: "SAN MATEO", label: "SAN MATEO" }, { value: "SAN MIGUEL", label: "SAN MIGUEL" }, { value: "SAN MIGUEL DE SEMA", label: "SAN MIGUEL DE SEMA" },
                    { value: "SAN ONOFRE", label: "SAN ONOFRE" }, { value: "SAN PABLO", label: "SAN PABLO" }, { value: "SAN PABLO DE BORBUR", label: "SAN PABLO DE BORBUR" }, { value: "SAN PEDRO", label: "SAN PEDRO" }, { value: "SAN PEDRO DE CARTAGO", label: "SAN PEDRO DE CARTAGO" },
                    { value: "SAN PEDRO DE LOS MILAGROS", label: "SAN PEDRO DE LOS MILAGROS" }, { value: "SAN PEDRO DE URABÁ", label: "SAN PEDRO DE URABÁ" }, { value: "SAN PELAYO", label: "SAN PELAYO" }, { value: "SAN RAFAEL", label: "SAN RAFAEL" }, { value: "SAN ROQUE", label: "SAN ROQUE" },
                    { value: "SAN SEBASTIÁN", label: "SAN SEBASTIÁN" }, { value: "SAN SEBASTIÁN DE BUENAVISTA", label: "SAN SEBASTIÁN DE BUENAVISTA" }, { value: "SAN VICENTE", label: "SAN VICENTE" }, { value: "SAN VICENTE DE CHUCURÍ", label: "SAN VICENTE DE CHUCURÍ" }, { value: "SAN VICENTE DEL CAGUÁN", label: "SAN VICENTE DEL CAGUÁN" },
                    { value: "SAN ZENÓN", label: "SAN ZENÓN" }, { value: "SANDONÁ", label: "SANDONÁ" }, { value: "SANTA ANA", label: "SANTA ANA" }, { value: "SANTA BÁRBARA", label: "SANTA BÁRBARA" }, { value: "SANTA BÁRBARA DE PINTO", label: "SANTA BÁRBARA DE PINTO" },
                    { value: "SANTA BÁRBARA ISCUANDÉ", label: "SANTA BÁRBARA ISCUANDÉ" }, { value: "SANTA CATALINA", label: "SANTA CATALINA" }, { value: "SANTA CRUZ", label: "SANTA CRUZ" }, { value: "SANTA FE DE ANTIOQUIA", label: "SANTA FE DE ANTIOQUIA" }, { value: "SANTA HELENA DEL OPÓN", label: "SANTA HELENA DEL OPÓN" },
                    { value: "SANTA ISABEL", label: "SANTA ISABEL" }, { value: "SANTA LUCÍA", label: "SANTA LUCÍA" }, { value: "SANTA MARÍA", label: "SANTA MARÍA" }, { value: "SANTA MARTA", label: "SANTA MARTA" }, { value: "SANTA ROSA", label: "SANTA ROSA" },
                    { value: "SANTA ROSA DE CABAL", label: "SANTA ROSA DE CABAL" }, { value: "SANTA ROSA DE LIMA O DEL NORTE", label: "SANTA ROSA DE LIMA O DEL NORTE" }, { value: "SANTA ROSA DE OSOS", label: "SANTA ROSA DE OSOS" }, { value: "SANTA ROSA DE VITERBO", label: "SANTA ROSA DE VITERBO" }, { value: "SANTA ROSA DEL SUR", label: "SANTA ROSA DEL SUR" },
                    { value: "SANTA ROSALÍA", label: "SANTA ROSALÍA" }, { value: "SANTA SOFÍA", label: "SANTA SOFÍA" }, { value: "SANTAFÉ DE ANTIOQUIA", label: "SANTAFÉ DE ANTIOQUIA" }, { value: "SANTAMARÍA", label: "SANTAMARÍA" }, { value: "SANTANA", label: "SANTANA" },
                    { value: "SANTANDER DE QUILICHAO", label: "SANTANDER DE QUILICHAO" }, { value: "SANTIAGO", label: "SANTIAGO" }, { value: "SANTIAGO DE TOLÚ", label: "SANTIAGO DE TOLÚ" }, { value: "SANTO DOMINGO", label: "SANTO DOMINGO" }, { value: "SANTO TOMÁS", label: "SANTO TOMÁS" },
                    { value: "SANTUARIO", label: "SANTUARIO" }, { value: "SAPUYES", label: "SAPUYES" }, { value: "SARAVENA", label: "SARAVENA" }, { value: "SARDINATA", label: "SARDINATA" }, { value: "SASAIMA", label: "SASAIMA" },
                    { value: "SATIVANORTE", label: "SATIVANORTE" }, { value: "SATIVASUR", label: "SATIVASUR" }, { value: "SEGOVIA", label: "SEGOVIA" }, { value: "SESQUILÉ", label: "SESQUILÉ" }, { value: "SEVILLA", label: "SEVILLA" },
                    { value: "SIACHOQUE", label: "SIACHOQUE" }, { value: "SIBATÉ", label: "SIBATÉ" }, { value: "SIBUNDOY", label: "SIBUNDOY" }, { value: "SILOS", label: "SILOS" }, { value: "SILVANIA", label: "SILVANIA" },
                    { value: "SILVIA", label: "SILVIA" }, { value: "SIMACOTA", label: "SIMACOTA" }, { value: "SIMIJACA", label: "SIMIJACA" }, { value: "SIMITÍ", label: "SIMITÍ" }, { value: "SINCÉ", label: "SINCÉ" },
                    { value: "SINCELEJO", label: "SINCELEJO" }, { value: "SIPÍ", label: "SIPÍ" }, { value: "SITIO NUEVO", label: "SITIO NUEVO" }, { value: "SOACHA", label: "SOACHA" }, { value: "SOATÁ", label: "SOATÁ" },
                    { value: "SOCHA", label: "SOCHA" }, { value: "SOCORRO", label: "SOCORRO" }, { value: "SOCOTÁ", label: "SOCOTÁ" }, { value: "SOGAMOSO", label: "SOGAMOSO" }, { value: "SOLANO", label: "SOLANO" },
                    { value: "SOLEDAD", label: "SOLEDAD" }, { value: "SOLITA", label: "SOLITA" }, { value: "SOMONDOCO", label: "SOMONDOCO" }, { value: "SONSÓN", label: "SONSÓN" }, { value: "SOPETRÁN", label: "SOPETRÁN" },
                    { value: "SOPLAVIENTO", label: "SOPLAVIENTO" }, { value: "SOPÓ", label: "SOPÓ" }, { value: "SORA", label: "SORA" }, { value: "SORACÁ", label: "SORACÁ" }, { value: "SOTAQUIRÁ", label: "SOTAQUIRÁ" },
                    { value: "SOTARÁ", label: "SOTARÁ" }, { value: "SUAITA", label: "SUAITA" }, { value: "SUAN", label: "SUAN" }, { value: "SUÁREZ", label: "SUÁREZ" }, { value: "SUAZA", label: "SUAZA" },
                    { value: "SUBACHOQUE", label: "SUBACHOQUE" }, { value: "SUCRE", label: "SUCRE" }, { value: "SUESCA", label: "SUESCA" }, { value: "SUPATÁ", label: "SUPATÁ" }, { value: "SUPÍA", label: "SUPÍA" },
                    { value: "SURATÁ", label: "SURATÁ" }, { value: "SUSA", label: "SUSA" }, { value: "SUSACÓN", label: "SUSACÓN" }, { value: "SUTAMARCHÁN", label: "SUTAMARCHÁN" }, { value: "SUTATAUSA", label: "SUTATAUSA" },
                    { value: "SUTATENZA", label: "SUTATENZA" }, { value: "TABIO", label: "TABIO" }, { value: "TADÓ", label: "TADÓ" }, { value: "TALAIGANUEVA", label: "TALAIGANUEVA" }, { value: "TAMALAMEQUE", label: "TAMALAMEQUE" },
                    { value: "TÁMARA", label: "TÁMARA" }, { value: "TAME", label: "TAME" }, { value: "TÁMESIS", label: "TÁMESIS" }, { value: "TAMINANGO", label: "TAMINANGO" }, { value: "TANGUA", label: "TANGUA" },
                    { value: "TARAIRA", label: "TARAIRA" }, { value: "TARAZÁ", label: "TARAZÁ" }, { value: "TARQUÍ", label: "TARQUÍ" }, { value: "TARSO", label: "TARSO" }, { value: "TASCO", label: "TASCO" },
                    { value: "TAURAMENA", label: "TAURAMENA" }, { value: "TAUSA", label: "TAUSA" }, { value: "TELLO", label: "TELLO" }, { value: "TENA", label: "TENA" }, { value: "TENERIFE", label: "TENERIFE" },
                    { value: "TENJO", label: "TENJO" }, { value: "TENZA", label: "TENZA" }, { value: "TEORAMA", label: "TEORAMA" }, { value: "TERUEL", label: "TERUEL" }, { value: "TESALIA", label: "TESALIA" },
                    { value: "TIBACUY", label: "TIBACUY" }, { value: "TIBANÁ", label: "TIBANÁ" }, { value: "TIBASOSA", label: "TIBASOSA" }, { value: "TIBIRITA", label: "TIBIRITA" }, { value: "TIBÚ", label: "TIBÚ" },
                    { value: "TIERRALTA", label: "TIERRALTA" }, { value: "TIMANÁ", label: "TIMANÁ" }, { value: "TIMBÍO", label: "TIMBÍO" }, { value: "TIMBIQUÍ", label: "TIMBIQUÍ" }, { value: "TINJACÁ", label: "TINJACÁ" },
                    { value: "TIPACOQUE", label: "TIPACOQUE" }, { value: "TIQUISIO", label: "TIQUISIO" }, { value: "TITIRIBÍ", label: "TITIRIBÍ" }, { value: "TOCA", label: "TOCA" }, { value: "TOCAIMA", label: "TOCAIMA" },
                    { value: "TOCANCIPÁ", label: "TOCANCIPÁ" }, { value: "TOGÜÍ", label: "TOGÜÍ" }, { value: "TOLEDO", label: "TOLEDO" }, { value: "TOLÚ VIEJO", label: "TOLÚ VIEJO" }, { value: "TONA", label: "TONA" },
                    { value: "TÓPAGA", label: "TÓPAGA" }, { value: "TOPAIPÍ", label: "TOPAIPÍ" }, { value: "TORIBÍO", label: "TORIBÍO" }, { value: "TORO", label: "TORO" }, { value: "TOTA", label: "TOTA" },
                    { value: "TOTORÓ", label: "TOTORÓ" }, { value: "TRINIDAD", label: "TRINIDAD" }, { value: "TRUJILLO", label: "TRUJILLO" }, { value: "TUBARÁ", label: "TUBARÁ" }, { value: "TUCHÍN", label: "TUCHÍN" },
                    { value: "TULUÁ", label: "TULUÁ" }, { value: "TUMACO", label: "TUMACO" }, { value: "TUNJA", label: "TUNJA" }, { value: "TUNUNGUÁ", label: "TUNUNGUÁ" }, { value: "TÚQUERRES", label: "TÚQUERRES" },
                    { value: "TURBACO", label: "TURBACO" }, { value: "TURBANÁ", label: "TURBANÁ" }, { value: "TURBO", label: "TURBO" }, { value: "TURMEQUÉ", label: "TURMEQUÉ" }, { value: "TUTA", label: "TUTA" },
                    { value: "TUTAZÁ", label: "TUTAZÁ" }, { value: "UBALÁ", label: "UBALÁ" }, { value: "UBAQUE", label: "UBAQUE" }, { value: "UBATÉ", label: "UBATÉ" }, { value: "ULLOA", label: "ULLOA" },
                    { value: "ÚMBITA ", label: "ÚMBITA " }, { value: "UNE", label: "UNE" }, { value: "UNGUÍA", label: "UNGUÍA" }, { value: "UNIÓN PANAMERICANA", label: "UNIÓN PANAMERICANA" }, { value: "URAMITA", label: "URAMITA" },
                    { value: "URIBÍA", label: "URIBÍA" }, { value: "URRAO", label: "URRAO" }, { value: "URUMITA", label: "URUMITA" }, { value: "USIACURÍ", label: "USIACURÍ" }, { value: "ÚTICA", label: "ÚTICA" },
                    { value: "VALDIVIA", label: "VALDIVIA" }, { value: "VALENCIA", label: "VALENCIA" }, { value: "VALLE DE GUAMUEZ", label: "VALLE DE GUAMUEZ" }, { value: "VALLE DE SAN JOSÉ", label: "VALLE DE SAN JOSÉ" }, { value: "VALLE DE SAN JUAN", label: "VALLE DE SAN JUAN" },
                    { value: "VALLEDUPAR", label: "VALLEDUPAR" }, { value: "VALPARAÍSO", label: "VALPARAÍSO" }, { value: "VEGACHÍ", label: "VEGACHÍ" }, { value: "VÉLEZ", label: "VÉLEZ" }, { value: "VENADILLO", label: "VENADILLO" },
                    { value: "VENECIA", label: "VENECIA" }, { value: "VENTAQUEMADA", label: "VENTAQUEMADA" }, { value: "VERGARA", label: "VERGARA" }, { value: "VERSALLES", label: "VERSALLES" }, { value: "VETAS", label: "VETAS" },
                    { value: "VIANÍ", label: "VIANÍ" }, { value: "VICTORIA", label: "VICTORIA" }, { value: "VIGÍA DEL FUERTE", label: "VIGÍA DEL FUERTE" }, { value: "VIJES", label: "VIJES" }, { value: "VILLA DE LEYVA", label: "VILLA DE LEYVA" },
                    { value: "VILLA HERMOSA", label: "VILLA HERMOSA" }, { value: "VILLA RICA", label: "VILLA RICA" }, { value: "VILLA ROSARIO", label: "VILLA ROSARIO" }, { value: "VILLACARO", label: "VILLACARO" }, { value: "VILLAGARZÓN", label: "VILLAGARZÓN" },
                    { value: "VILLAGÓMEZ", label: "VILLAGÓMEZ" }, { value: "VILLAMARÍA", label: "VILLAMARÍA" }, { value: "VILLANUEVA", label: "VILLANUEVA" }, { value: "VILLAPINZÓN", label: "VILLAPINZÓN" }, { value: "VILLAVICENCIO", label: "VILLAVICENCIO" },
                    { value: "VILLAVIEJA", label: "VILLAVIEJA" }, { value: "VILLETA", label: "VILLETA" }, { value: "VIOTÁ", label: "VIOTÁ" }, { value: "VIRACACHA", label: "VIRACACHA" }, { value: "VISTA HERMOSA", label: "VISTA HERMOSA" },
                    { value: "VITERBO", label: "VITERBO" }, { value: "YACOPÍ", label: "YACOPÍ" }, { value: "YACUANQUER", label: "YACUANQUER" }, { value: "YAGUARA", label: "YAGUARA" }, { value: "YALÍ", label: "YALÍ" },
                    { value: "YARUMAL", label: "YARUMAL" }, { value: "YOLOMBÓ", label: "YOLOMBÓ" }, { value: "YONDÓ", label: "YONDÓ" }, { value: "YOPAL", label: "YOPAL" }, { value: "YOTOCO", label: "YOTOCO" },
                    { value: "YUMBO", label: "YUMBO" }, { value: "ZAMBRANO", label: "ZAMBRANO" }, { value: "ZAPATOCA", label: "ZAPATOCA" }, { value: "ZAPAYÁN", label: "ZAPAYÁN" }, { value: "ZARAGOZA", label: "ZARAGOZA" },
                    { value: "ZARZAL", label: "ZARZAL" }, { value: "ZETAQUIRÁ", label: "ZETAQUIRÁ" }, { value: "ZIPACÓN", label: "ZIPACÓN" }, { value: "ZIPAQUIRÁ", label: "ZIPAQUIRÁ" }, { value: "ZONA BANANERA", label: "ZONA BANANERA" }
                ],
                distrito: [
                    { value: "ALTAS CORTES", label: "ALTAS CORTES" }, { value: "ANTIOQUIA", label: "ANTIOQUIA" }, { value: "ARAUCA", label: "ARAUCA" }, { value: "ARMENIA", label: "ARMENIA" }, { value: "ATLÁNTICO", label: "ATLÁNTICO" },
                    { value: "BARRANQUILLA", label: "BARRANQUILLA" }, { value: "BOGOTÁ", label: "BOGOTÁ" }, { value: "BOLÍVAR", label: "BOLÍVAR" }, { value: "BOYACÁ", label: "BOYACÁ" }, { value: "BUCARAMANGA", label: "BUCARAMANGA" },
                    { value: "BUGA", label: "BUGA" }, { value: "CALDAS", label: "CALDAS" }, { value: "CALI", label: "CALI" }, { value: "CAQUETÁ", label: "CAQUETÁ" }, { value: "CARTAGENA", label: "CARTAGENA" },
                    { value: "CASANARE", label: "CASANARE" }, { value: "CAUCA", label: "CAUCA" }, { value: "CAUCA ", label: "CAUCA " }, { value: "CESAR", label: "CESAR" }, { value: "CHOCÓ", label: "CHOCÓ" },
                    { value: "CÓRDOBA", label: "CÓRDOBA" }, { value: "CÚCUTA", label: "CÚCUTA" }, { value: "CUNDINAMARCA", label: "CUNDINAMARCA" }, { value: "FLORENCIA", label: "FLORENCIA" }, { value: "HUILA", label: "HUILA" },
                    { value: "IBAGUÉ", label: "IBAGUÉ" }, { value: "LA GUAJIRA", label: "LA GUAJIRA" }, { value: "MAGDALENA", label: "MAGDALENA" }, { value: "MANIZALES", label: "MANIZALES" }, { value: "MEDELLÍN", label: "MEDELLÍN" },
                    { value: "META", label: "META" }, { value: "MOCOA", label: "MOCOA" }, { value: "MONTERÍA", label: "MONTERÍA" }, { value: "NARIÑO", label: "NARIÑO" }, { value: "NEIVA", label: "NEIVA" },
                    { value: "NORTE DE SANTANDER", label: "NORTE DE SANTANDER" }, { value: "PAMPLONA", label: "PAMPLONA" }, { value: "PASTO", label: "PASTO" }, { value: "PEREIRA", label: "PEREIRA" }, { value: "POPAYÁN", label: "POPAYÁN" },
                    { value: "PUTUMAYO", label: "PUTUMAYO" }, { value: "QUIBDÓ", label: "QUIBDÓ" }, { value: "QUINDÍO", label: "QUINDÍO" }, { value: "RIOHACHA", label: "RIOHACHA" }, { value: "RISARALDA", label: "RISARALDA" },
                    { value: "SAN ANDRÉS", label: "SAN ANDRÉS" }, { value: "SAN GIL", label: "SAN GIL" }, { value: "SAN JOSÉ DEL GUAVIARE", label: "SAN JOSÉ DEL GUAVIARE" }, { value: "SANTA MARTA", label: "SANTA MARTA" }, { value: "SANTA ROSA DE VITERBO", label: "SANTA ROSA DE VITERBO" },
                    { value: "SANTANDER", label: "SANTANDER" }, { value: "SINCELEJO", label: "SINCELEJO" }, { value: "SUCRE", label: "SUCRE" }, { value: "TOLIMA", label: "TOLIMA" }, { value: "TUNJA", label: "TUNJA" },
                    { value: "VALLE DEL CAUCA", label: "VALLE DEL CAUCA" }, { value: "VALLEDUPAR", label: "VALLEDUPAR" }, { value: "VILLAVICENCIO", label: "VILLAVICENCIO" }, { value: "YOPAL", label: "YOPAL" }
                ],
                circuito: [
                    { value: "ABEJORRAL", label: "ABEJORRAL" }, { value: "ACACÍAS", label: "ACACÍAS" }, { value: "AGUACHICA", label: "AGUACHICA" }, { value: "AGUADAS", label: "AGUADAS" }, { value: "ALTAS CORTES", label: "ALTAS CORTES" },
                    { value: "AMAGÁ", label: "AMAGÁ" }, { value: "AMALFI", label: "AMALFI" }, { value: "ANDES", label: "ANDES" }, { value: "ANSERMA", label: "ANSERMA" }, { value: "ANTIOQUIA", label: "ANTIOQUIA" },
                    { value: "APARTADÓ", label: "APARTADÓ" }, { value: "APÍA", label: "APÍA" }, { value: "ARAUCA", label: "ARAUCA" }, { value: "ARMENIA", label: "ARMENIA" }, { value: "ATLÁNTICO", label: "ATLÁNTICO" },
                    { value: "AYAPEL", label: "AYAPEL" }, { value: "BAHÍA SOLANO", label: "BAHÍA SOLANO" }, { value: "BARBACOAS", label: "BARBACOAS" }, { value: "BARRANCABERMEJA", label: "BARRANCABERMEJA" }, { value: "BARRANQUILLA", label: "BARRANQUILLA" },
                    { value: "BELÉN DE LOS ANDAQUÍES", label: "BELÉN DE LOS ANDAQUÍES" }, { value: "BELÉN DE UMBRÍA", label: "BELÉN DE UMBRÍA" }, { value: "BELLO", label: "BELLO" }, { value: "BOGOTÁ", label: "BOGOTÁ" }, { value: "BOLÍVAR", label: "BOLÍVAR" },
                    { value: "BOYACÁ", label: "BOYACÁ" }, { value: "BUCARAMANGA", label: "BUCARAMANGA" }, { value: "BUENAVENTURA", label: "BUENAVENTURA" }, { value: "BUGA", label: "BUGA" }, { value: "CALARCÁ", label: "CALARCÁ" },
                    { value: "CALDAS", label: "CALDAS" }, { value: "CALI", label: "CALI" }, { value: "CALOTO", label: "CALOTO" }, { value: "CAQUETÁ", label: "CAQUETÁ" }, { value: "CÁQUEZA", label: "CÁQUEZA" },
                    { value: "CARMEN DE BOLÍVAR", label: "CARMEN DE BOLÍVAR" }, { value: "CARTAGENA", label: "CARTAGENA" }, { value: "CARTAGO", label: "CARTAGO" }, { value: "CASANARE", label: "CASANARE" }, { value: "CAUCA", label: "CAUCA" },
                    { value: "CAUCASIA", label: "CAUCASIA" }, { value: "CERETÉ", label: "CERETÉ" }, { value: "CESAR", label: "CESAR" }, { value: "CHAPARRAL", label: "CHAPARRAL" }, { value: "CHARALÁ", label: "CHARALÁ" },
                    { value: "CHINCHINÁ", label: "CHINCHINÁ" }, { value: "CHINÚ", label: "CHINÚ" }, { value: "CHIQUINQUIRÁ", label: "CHIQUINQUIRÁ" }, { value: "CHIRIGUANÁ", label: "CHIRIGUANÁ" }, { value: "CHOCÓ", label: "CHOCÓ" },
                    { value: "CHOCONTÁ", label: "CHOCONTÁ" }, { value: "CIÉNAGA", label: "CIÉNAGA" }, { value: "CIMITARRA", label: "CIMITARRA" }, { value: "CISNEROS", label: "CISNEROS" }, { value: "CONCORDIA", label: "CONCORDIA" },
                    { value: "CÓRDOBA", label: "CÓRDOBA" }, { value: "COROZAL", label: "COROZAL" }, { value: "CÚCUTA", label: "CÚCUTA" }, { value: "CUNDINAMARCA", label: "CUNDINAMARCA" }, { value: "DABEIBA", label: "DABEIBA" },
                    { value: "DOSQUEBRADAS", label: "DOSQUEBRADAS" }, { value: "DUITAMA", label: "DUITAMA" }, { value: "EL BAGRE", label: "EL BAGRE" }, { value: "EL BANCO", label: "EL BANCO" }, { value: "EL COCUY", label: "EL COCUY" },
                    { value: "EL SANTUARIO", label: "EL SANTUARIO" }, { value: "ENVIGADO", label: "ENVIGADO" }, { value: "ESPINAL", label: "ESPINAL" }, { value: "FACATATIVÁ", label: "FACATATIVÁ" }, { value: "FLORENCIA", label: "FLORENCIA" },
                    { value: "FREDONIA", label: "FREDONIA" }, { value: "FRESNO", label: "FRESNO" }, { value: "FRONTINO", label: "FRONTINO" }, { value: "FUNDACIÓN", label: "FUNDACIÓN" }, { value: "FUNZA", label: "FUNZA" },
                    { value: "FUSAGASUGÁ", label: "FUSAGASUGÁ" }, { value: "GACHETÁ", label: "GACHETÁ" }, { value: "GARAGOA", label: "GARAGOA" }, { value: "GARZÓN", label: "GARZÓN" }, { value: "GIRARDOT", label: "GIRARDOT" },
                    { value: "GIRARDOTA", label: "GIRARDOTA" }, { value: "GRANADA", label: "GRANADA" }, { value: "GUADUAS", label: "GUADUAS" }, { value: "GUAMO", label: "GUAMO" }, { value: "GUAPI", label: "GUAPI" },
                    { value: "GUATEQUE", label: "GUATEQUE" }, { value: "HONDA", label: "HONDA" }, { value: "HUILA", label: "HUILA" }, { value: "IBAGUÉ", label: "IBAGUÉ" }, { value: "INÍRIDA", label: "INÍRIDA" },
                    { value: "IPIALES", label: "IPIALES" }, { value: "ISTMINA", label: "ISTMINA" }, { value: "ITAGÜÍ", label: "ITAGÜÍ" }, { value: "ITUANGO", label: "ITUANGO" }, { value: "JERICÓ", label: "JERICÓ" },
                    { value: "LA CEJA", label: "LA CEJA" }, { value: "LA CRUZ", label: "LA CRUZ" }, { value: "LA DORADA", label: "LA DORADA" }, { value: "LA GUAJIRA", label: "LA GUAJIRA" }, { value: "LA MESA", label: "LA MESA" },
                    { value: "LA PALMA", label: "LA PALMA" }, { value: "LA PLATA", label: "LA PLATA" }, { value: "LA UNIÓN", label: "LA UNIÓN" }, { value: "LA VIRGINIA", label: "LA VIRGINIA" }, { value: "LÉRIDA", label: "LÉRIDA" },
                    { value: "LETICIA", label: "LETICIA" }, { value: "LÍBANO", label: "LÍBANO" }, { value: "LORICA", label: "LORICA" }, { value: "LOS PATIOS", label: "LOS PATIOS" }, { value: "MAGANGUÉ", label: "MAGANGUÉ" },
                    { value: "MAGDALENA", label: "MAGDALENA" }, { value: "MAICAO", label: "MAICAO" }, { value: "MAJAGUAL", label: "MAJAGUAL" }, { value: "MÁLAGA", label: "MÁLAGA" }, { value: "MANIZALES", label: "MANIZALES" },
                    { value: "MANZANARES", label: "MANZANARES" }, { value: "MARINILLA", label: "MARINILLA" }, { value: "MEDELLÍN", label: "MEDELLÍN" }, { value: "MELGAR", label: "MELGAR" }, { value: "META", label: "META" },
                    { value: "MIRAFLORES", label: "MIRAFLORES" }, { value: "MITÚ", label: "MITÚ" }, { value: "MOCOA", label: "MOCOA" }, { value: "MOMPÓS", label: "MOMPÓS" }, { value: "MONIQUIRÁ", label: "MONIQUIRÁ" },
                    { value: "MONTELÍBANO", label: "MONTELÍBANO" }, { value: "MONTERÍA", label: "MONTERÍA" }, { value: "MONTERREY", label: "MONTERREY" }, { value: "NARIÑO", label: "NARIÑO" }, { value: "NEIVA", label: "NEIVA" },
                    { value: "NORTE DE SANTANDER", label: "NORTE DE SANTANDER" }, { value: "OCAÑA", label: "OCAÑA" }, { value: "OROCUÉ", label: "OROCUÉ" }, { value: "PACHO", label: "PACHO" }, { value: "PALMIRA", label: "PALMIRA" },
                    { value: "PAMPLONA", label: "PAMPLONA" }, { value: "PASTO", label: "PASTO" }, { value: "PATÍA - EL BORDO", label: "PATÍA - EL BORDO" }, { value: "PAZ DE ARIPORO", label: "PAZ DE ARIPORO" }, { value: "PAZ DE RÍO", label: "PAZ DE RÍO" },
                    { value: "PAZ DEL RÍO", label: "PAZ DEL RÍO" }, { value: "PENSILVANIA", label: "PENSILVANIA" }, { value: "PEREIRA", label: "PEREIRA" }, { value: "PITALITO", label: "PITALITO" }, { value: "PIVIJAY", label: "PIVIJAY" },
                    { value: "PLANETA RICA", label: "PLANETA RICA" }, { value: "PLATO", label: "PLATO" }, { value: "POPAYÁN", label: "POPAYÁN" }, { value: "PUENTE NACIONAL", label: "PUENTE NACIONAL" }, { value: "PUERTO ASÍS", label: "PUERTO ASÍS" },
                    { value: "PUERTO BERRIO", label: "PUERTO BERRIO" }, { value: "PUERTO BERRÍO", label: "PUERTO BERRÍO" }, { value: "PUERTO BOYACÁ", label: "PUERTO BOYACÁ" }, { value: "PUERTO CARREÑO", label: "PUERTO CARREÑO" }, { value: "PUERTO COLOMBIA", label: "PUERTO COLOMBIA" },
                    { value: "PUERTO LÓPEZ", label: "PUERTO LÓPEZ" }, { value: "PUERTO RICO", label: "PUERTO RICO" }, { value: "PUERTO TEJADA", label: "PUERTO TEJADA" }, { value: "PURIFICACIÓN", label: "PURIFICACIÓN" }, { value: "QUIBDÓ", label: "QUIBDÓ" },
                    { value: "QUINCHÍA", label: "QUINCHÍA" }, { value: "QUINDÍO", label: "QUINDÍO" }, { value: "RAMIRIQUÍ", label: "RAMIRIQUÍ" }, { value: "RIOHACHA", label: "RIOHACHA" }, { value: "RIONEGRO", label: "RIONEGRO" },
                    { value: "RIOSUCIO", label: "RIOSUCIO" }, { value: "RISARALDA", label: "RISARALDA" }, { value: "ROLDANILLO", label: "ROLDANILLO" }, { value: "SABANALARGA", label: "SABANALARGA" }, { value: "SAHAGÚN", label: "SAHAGÚN" },
                    { value: "SALAMINA", label: "SALAMINA" }, { value: "SAMANIEGO", label: "SAMANIEGO" }, { value: "SAN ANDRÉS", label: "SAN ANDRÉS" }, { value: "SAN GIL", label: "SAN GIL" }, { value: "SAN JOSÉ DEL GUAVIARE", label: "SAN JOSÉ DEL GUAVIARE" },
                    { value: "SAN JUAN DEL CESAR", label: "SAN JUAN DEL CESAR" }, { value: "SAN MARCOS", label: "SAN MARCOS" }, { value: "SAN MARTÍN", label: "SAN MARTÍN" }, { value: "SAN PEDRO DE LOS MILAGROS", label: "SAN PEDRO DE LOS MILAGROS" }, { value: "SAN VICENTE DE CHUCURÍ", label: "SAN VICENTE DE CHUCURÍ" },
                    { value: "SANTA BÁRBARA", label: "SANTA BÁRBARA" }, { value: "SANTA FE DE ANTIOQUIA", label: "SANTA FE DE ANTIOQUIA" }, { value: "SANTA MARTA", label: "SANTA MARTA" }, { value: "SANTA ROSA DE CABAL", label: "SANTA ROSA DE CABAL" }, { value: "SANTA ROSA DE OSOS", label: "SANTA ROSA DE OSOS" },
                    { value: "SANTA ROSA DE VITERBO", label: "SANTA ROSA DE VITERBO" }, { value: "SANTANDER", label: "SANTANDER" }, { value: "SANTANDER DE QUILICHAO", label: "SANTANDER DE QUILICHAO" }, { value: "SARAVENA", label: "SARAVENA" }, { value: "SEGOVIA", label: "SEGOVIA" },
                    { value: "SEVILLA", label: "SEVILLA" }, { value: "SIBUNDOY", label: "SIBUNDOY" }, { value: "SILVIA", label: "SILVIA" }, { value: "SIMITÍ", label: "SIMITÍ" }, { value: "SINCÉ", label: "SINCÉ" },
                    { value: "SINCELEJO", label: "SINCELEJO" }, { value: "SOACHA", label: "SOACHA" }, { value: "SOATÁ", label: "SOATÁ" }, { value: "SOCHA", label: "SOCHA" }, { value: "SOCORRO", label: "SOCORRO" },
                    { value: "SOGAMOSO", label: "SOGAMOSO" }, { value: "SOLEDAD", label: "SOLEDAD" }, { value: "SONSÓN", label: "SONSÓN" }, { value: "SOPETRÁN", label: "SOPETRÁN" }, { value: "SUCRE", label: "SUCRE" },
                    { value: "TÁMESIS", label: "TÁMESIS" }, { value: "TITIRIBÍ", label: "TITIRIBÍ" }, { value: "TOLIMA", label: "TOLIMA" }, { value: "TULUÁ", label: "TULUÁ" }, { value: "TUMACO", label: "TUMACO" },
                    { value: "TUNJA", label: "TUNJA" }, { value: "TÚQUERRES", label: "TÚQUERRES" }, { value: "TURBACO", label: "TURBACO" }, { value: "TURBO", label: "TURBO" }, { value: "UBATÉ", label: "UBATÉ" },
                    { value: "URRAO", label: "URRAO" }, { value: "VALLE DEL CAUCA", label: "VALLE DEL CAUCA" }, { value: "VALLEDUPAR", label: "VALLEDUPAR" }, { value: "VÉLEZ", label: "VÉLEZ" }, { value: "VILLANUEVA", label: "VILLANUEVA" },
                    { value: "VILLAVICENCIO", label: "VILLAVICENCIO" }, { value: "VILLETA", label: "VILLETA" }, { value: "YARUMAL", label: "YARUMAL" }, { value: "YOLOMBÓ", label: "YOLOMBÓ" }, { value: "YOPAL", label: "YOPAL" },
                    { value: "ZIPAQUIRÁ", label: "ZIPAQUIRÁ" }
                ],
                consejoseccional: [
                    { value: "ALTAS CORTES", label: "ALTAS CORTES" }, { value: "ANTIOQUIA", label: "ANTIOQUIA" }, { value: "ATLÁNTICO", label: "ATLÁNTICO" }, { value: "BOGOTÁ", label: "BOGOTÁ" }, { value: "BOLÍVAR", label: "BOLÍVAR" },
                    { value: "BOYACÁ - CASANARE", label: "BOYACÁ - CASANARE" }, { value: "CALDAS", label: "CALDAS" }, { value: "CAQUETÁ", label: "CAQUETÁ" }, { value: "CAUCA", label: "CAUCA" }, { value: "CESAR", label: "CESAR" },
                    { value: "CHOCÓ", label: "CHOCÓ" }, { value: "CÓRDOBA", label: "CÓRDOBA" }, { value: "CUNDINAMARCA", label: "CUNDINAMARCA" }, { value: "HUILA", label: "HUILA" }, { value: "LA GUAJIRA", label: "LA GUAJIRA" },
                    { value: "MAGDALENA", label: "MAGDALENA" }, { value: "META", label: "META" }, { value: "NARIÑO", label: "NARIÑO" }, { value: "NORTE DE SANTANDER", label: "NORTE DE SANTANDER" }, { value: "QUINDÍO", label: "QUINDÍO" },
                    { value: "RISARALDA", label: "RISARALDA" }, { value: "SANTANDER", label: "SANTANDER" }, { value: "SUCRE", label: "SUCRE" }, { value: "TOLIMA", label: "TOLIMA" }, { value: "VALLE DEL CAUCA", label: "VALLE DEL CAUCA" }
                ],
                especialidad: [
                    { value: "CIVIL", label: "CIVIL" }, { value: "CIVIL - FAMILIA", label: "CIVIL - FAMILIA" }, { value: "CIVIL - FAMILIA - LABORAL", label: "CIVIL - FAMILIA - LABORAL" }, { value: "CIVIL CON COMPETENCIA EN ASUNTOS LABORALES", label: "CIVIL CON COMPETENCIA EN ASUNTOS LABORALES" }, { value: "CIVIL EJECUCIÓN", label: "CIVIL EJECUCIÓN" },
                    { value: "CIVIL PEQUEÑAS CAUSAS", label: "CIVIL PEQUEÑAS CAUSAS" }, { value: "CIVIL RESTITUCIÓN DE TIERRAS", label: "CIVIL RESTITUCIÓN DE TIERRAS" }, { value: "CONSTITUCIONAL", label: "CONSTITUCIONAL" }, { value: "DISCIPLINARIA", label: "DISCIPLINARIA" }, { value: "EJECUCIÓN DE PENAS Y MEDIDAS DE SEGURIDAD", label: "EJECUCIÓN DE PENAS Y MEDIDAS DE SEGURIDAD" },
                    { value: "FAMILIA", label: "FAMILIA" }, { value: "FAMILIA EJECUCIÓN", label: "FAMILIA EJECUCIÓN" }, { value: "LABORAL", label: "LABORAL" }, { value: "PENAL", label: "PENAL" }, { value: "PENAL - FONCOLPUERTOS", label: "PENAL - FONCOLPUERTOS" },
                    { value: "PENAL CON FUNCIÓN DE CONTROL DE GARANTÍAS", label: "PENAL CON FUNCIÓN DE CONTROL DE GARANTÍAS" }, { value: "PENAL CON FUNCIÓN DE CONTROL DE GARANTÍAS – BACRIM", label: "PENAL CON FUNCIÓN DE CONTROL DE GARANTÍAS – BACRIM" }, { value: "PENAL ESPECIALIZADO", label: "PENAL ESPECIALIZADO" }, { value: "PENAL ESPECIALIZADO – LÍDERES SOCIALES", label: "PENAL ESPECIALIZADO – LÍDERES SOCIALES" }, { value: "PENAL ESPECIALIZADO - OIT", label: "PENAL ESPECIALIZADO - OIT" },
                    { value: "PENAL ESPECIALIZADO DE EXTINCIÓN DE DOMINIO", label: "PENAL ESPECIALIZADO DE EXTINCIÓN DE DOMINIO" }, { value: "PENAL JUSTICIA Y PAZ - CONOCIMIENTO", label: "PENAL JUSTICIA Y PAZ - CONOCIMIENTO" }, { value: "PENAL JUSTICIA Y PAZ - CONTROL DE GARANTÍAS", label: "PENAL JUSTICIA Y PAZ - CONTROL DE GARANTÍAS" }, { value: "PENAL JUSTICIA Y PAZ - EJECUCIÓN DE SENTENCIAS", label: "PENAL JUSTICIA Y PAZ - EJECUCIÓN DE SENTENCIAS" }, { value: "PENAL PARA ADOLESCENTES CON FUNCIÓN DE CONOCIMIENTO", label: "PENAL PARA ADOLESCENTES CON FUNCIÓN DE CONOCIMIENTO" },
                    { value: "PENAL PARA ADOLESCENTES CON FUNCIÓN DE CONTROL DE GARANTÍAS", label: "PENAL PARA ADOLESCENTES CON FUNCIÓN DE CONTROL DE GARANTÍAS" }, { value: "PROMISCUO", label: "PROMISCUO" }, { value: "PROMISCUO DE FAMILIA", label: "PROMISCUO DE FAMILIA" }, { value: "SALA DE CONSULTA Y SERVICIO CIVIL", label: "SALA DE CONSULTA Y SERVICIO CIVIL" }, { value: "SALA PENAL ESPECIAL DE INSTRUCCIÓN", label: "SALA PENAL ESPECIAL DE INSTRUCCIÓN" },
                    { value: "SALA PENAL ESPECIAL DE PRIMERA INSTANCIA", label: "SALA PENAL ESPECIAL DE PRIMERA INSTANCIA" }, { value: "SALA ÚNICA", label: "SALA ÚNICA" }, { value: "SECCIÓN CUARTA", label: "SECCIÓN CUARTA" }, { value: "SECCIÓN PRIMERA", label: "SECCIÓN PRIMERA" }, { value: "SECCIÓN QUINTA", label: "SECCIÓN QUINTA" },
                    { value: "SECCIÓN SEGUNDA", label: "SECCIÓN SEGUNDA" }, { value: "SECCIÓN TERCERA", label: "SECCIÓN TERCERA" }, { value: "SIN SECCIÓN", label: "SIN SECCIÓN" }
                ],
                tipo: [
                    { value: "Permanente", label: "Permanente" },{ value: "Descongestión", label: "Descongestión" }
                ]
            },
            despachos: [
                {
                    id: 1,
                    consejoseccional: "ANTIOQUIA",
                    jurisdiccion: "ORDINARIA",
                    deptomunicipio: "MEDELLÍN",
                    distrito: "MEDELLÍN",
                    circuito: "MEDELLÍN",
                    tipodespacho: "JUZGADO MUNICIPAL",
                    especialidad: "CIVIL",
                    tipo:"Descongestión",
                    codigoDespacho: "050014003801",                    
                    nombreDespacho: "JUZGADO 801 CIVIL MUNICIPAL TRANSITORIO DE MEDELLÍN",
                    fechaInicio: "2026-01-01",
                    fechaFin: "2026-12-31",
                    estado: "Activo",
                    adminPrimerNombre: "Carlos",
                    adminSegundoNombre: "Andrés",
                    adminPrimerApellido: "Pérez",
                    adminSegundoApellido: "Gómez",
                    adminCorreo: "cperez@cendoj.ramajudicial.gov.co",
                    adminPassword: "Temp2026*"
                },
                {
                    id: 2,
                    consejoseccional: "BOGOTÁ",
                    jurisdiccion: "ORDINARIA",
                    deptomunicipio: "BOGOTÁ",
                    distrito: "BOGOTÁ",
                    circuito: "BOGOTÁ",
                    tipodespacho: "JUZGADO DE CIRCUITO",
                    especialidad: "LABORAL",
                    tipo:"Descongestión",
                    codigoDespacho: "110013105801",
                    nombreDespacho: "JUZGADO 801 LABORAL TRANSITORIO DE BOGOTÁ",
                    fechaInicio: "2026-01-01",
                    fechaFin: "2026-12-31",
                    estado: "Activo",
                    adminPrimerNombre: "María",
                    adminSegundoNombre: "Elena",
                    adminPrimerApellido: "Rodríguez",
                    adminSegundoApellido: "Silva",
                    adminCorreo: "mrodriguez@cendoj.ramajudicial.gov.co",
                    adminPassword: "Temp2026*"
                },
                {
                    id: 3,
                    consejoseccional: "BOLÍVAR",
                    jurisdiccion: "ORDINARIA",
                    deptomunicipio: "CARTAGENA",
                    distrito: "CARTAGENA",
                    circuito: "CARTAGENA",
                    tipodespacho: "TRIBUNAL SUPERIOR",
                    especialidad: "CIVIL RESTITUCIÓN DE TIERRAS",
                    tipo:"Descongestión",
                    codigoDespacho: "130012221801",
                    nombreDespacho: "DESPACHO 801 TRANSITORIO DE LA SALA CIVIL ESPECIALIZADA EN RESTITUCIÓN DE TIERRAS DEL TRIBUNAL SUPERIOR DE CARTAGENA",
                    fechaInicio: "2026-02-01",
                    fechaFin: "2026-11-30",
                    estado: "Activo",
                    adminPrimerNombre: "Jorge",
                    adminSegundoNombre: "Luis",
                    adminPrimerApellido: "Martínez",
                    adminSegundoApellido: "Díaz",
                    adminCorreo: "jmartinez@cendoj.ramajudicial.gov.co",
                    adminPassword: "Temp2026*"
                },
                {
                    id: 4,
                    consejoseccional: "BOYACÁ - CASANARE",
                    jurisdiccion: "ORDINARIA",
                    deptomunicipio: "YOPAL",
                    distrito: "YOPAL",
                    circuito: "YOPAL",
                    tipodespacho: "JUZGADO MUNICIPAL",
                    especialidad: "LABORAL",
                    tipo:"Descongestión",
                    codigoDespacho: "850014005801",
                    nombreDespacho: "JUZGADO 801 LABORAL MUNICIPAL TRANSITORIO DE YOPAL",
                    fechaInicio: "2026-03-01",
                    fechaFin: "2026-12-31",
                    estado: "Activo",
                    adminPrimerNombre: "Ana",
                    adminSegundoNombre: "Lucía",
                    adminPrimerApellido: "López",
                    adminSegundoApellido: "Rojas",
                    adminCorreo: "alopez@cendoj.ramajudicial.gov.co",
                    adminPassword: "Temp2026*"
                },
                {
                    id: 5,
                    consejoseccional: "CALDAS",
                    jurisdiccion: "ORDINARIA",
                    deptomunicipio: "MANIZALES",
                    distrito: "MANIZALES",
                    circuito: "MANIZALES",
                    tipodespacho: "JUZGADO MUNICIPAL",
                    especialidad: "LABORAL",
                    tipo:"Descongestión",
                    codigoDespacho: "170014005801",
                    nombreDespacho: "JUZGADO 801 LABORAL MUNICIPAL TRANSITORIO DE MANIZALES",
                    fechaInicio: "2026-01-15",
                    fechaFin: "2026-12-31",
                    estado: "Activo",
                    adminPrimerNombre: "Luis",
                    adminSegundoNombre: "Fernando",
                    adminPrimerApellido: "Giraldo",
                    adminSegundoApellido: "Restrepo",
                    adminCorreo: "lgiraldo@cendoj.ramajudicial.gov.co",
                    adminPassword: "Temp2026*"
                },
                {
                    id: 6,
                    consejoseccional: "TOLIMA",
                    jurisdiccion: "ORDINARIA",
                    deptomunicipio: "IBAGUÉ",
                    distrito: "IBAGUÉ",
                    circuito: "IBAGUÉ",
                    tipodespacho: "JUZGADO MUNICIPAL",
                    especialidad: "LABORAL",
                    tipo:"Descongestión",
                    codigoDespacho: "730014005801",
                    nombreDespacho: "JUZGADO 801 LABORAL MUNICIPAL TRANSITORIO DE IBAGUÉ",
                    fechaInicio: "2026-01-01",
                    fechaFin: "2026-12-31",
                    estado: "Activo",
                    adminPrimerNombre: "Diana",
                    adminSegundoNombre: "Marcela",
                    adminPrimerApellido: "Torres",
                    adminSegundoApellido: "Mejía",
                    adminCorreo: "dtorres@cendoj.ramajudicial.gov.co",
                    adminPassword: "Temp2026*"
                }
            ]
        };