// =====================================================================
// RUNPD - Postulaciones de despachos permanentes recibidas por la UDAE
// (llegan desde registro_usuario_despacho_permanente.html)
// Los catálogos de los selects siguen viniendo de js/data.js (dbDatos)
// =====================================================================
const dbPostulaciones = {
    // Motivos frecuentes de rechazo (se pueden elegir y complementar)
    motivosRechazo: [
        "El código del despacho no corresponde al despacho indicado.",
        "El correo registrado no es institucional.",
        "El despacho ya se encuentra registrado en el sistema.",
        "Los datos territoriales (distrito, circuito o consejo) son inconsistentes.",
        "La persona registrada no es el administrador del despacho."
    ],

    solicitudes: [
        {
            id: 1,
            radicado: "SOL-2026-2879",
            fechaSolicitud: "2026-09-28",
            estado: "Pendiente",
            adminPrimerNombre: "Luis",
            adminSegundoNombre: "Fernando",
            adminPrimerApellido: "Giraldo",
            adminSegundoApellido: "Restrepo",
            adminCorreo: "lgiraldo@cendoj.ramajudicial.gov.co",
            jurisdiccion: "ORDINARIA",
            tipodespacho: "JUZGADO MUNICIPAL",
            deptomunicipio: "MEDELLÍN",
            consejoseccional: "ANTIOQUIA",
            distrito: "MEDELLÍN",
            circuito: "MEDELLÍN",
            especialidad: "CIVIL",
            tipo: "Permanente",
            codigoDespacho: "050014003003",
            nombreDespacho: "JUZGADO 003 CIVIL MUNICIPAL DE MEDELLÍN"
        },
        {
            id: 2,
            radicado: "SOL-2026-2890",
            fechaSolicitud: "2026-09-29",
            estado: "Pendiente",
            adminPrimerNombre: "Paola",
            adminSegundoNombre: "Andrea",
            adminPrimerApellido: "Suárez",
            adminSegundoApellido: "Rincón",
            adminCorreo: "psuarez.juzgado@gmail.com",
            jurisdiccion: "ORDINARIA",
            tipodespacho: "JUZGADO DE CIRCUITO",
            deptomunicipio: "BOGOTÁ",
            consejoseccional: "BOGOTÁ",
            distrito: "BOGOTÁ",
            circuito: "BOGOTÁ",
            especialidad: "FAMILIA",
            tipo: "Permanente",
            codigoDespacho: "110013110005",
            nombreDespacho: "JUZGADO 005 DE FAMILIA DE BOGOTÁ"
        },
        {
            id: 3,
            radicado: "SOL-2026-2861",
            fechaSolicitud: "2026-09-18",
            estado: "Pendiente",
            adminPrimerNombre: "Andrés",
            adminSegundoNombre: "",
            adminPrimerApellido: "Villegas",
            adminSegundoApellido: "Ospina",
            adminCorreo: "avillegas@cendoj.ramajudicial.gov.co",
            jurisdiccion: "ORDINARIA",
            tipodespacho: "JUZGADO MUNICIPAL",
            deptomunicipio: "MANIZALES",
            consejoseccional: "CALDAS",
            distrito: "MANIZALES",
            circuito: "MANIZALES",
            especialidad: "LABORAL",
            tipo: "Permanente",
            codigoDespacho: "170014005801",
            nombreDespacho: "JUZGADO 004 LABORAL MUNICIPAL DE MANIZALES"
        },
        {
            id: 4,
            radicado: "SOL-2026-2804",
            fechaSolicitud: "2026-06-10",
            estado: "Aprobado",
            fechaRespuesta: "2026-06-12",
            notificado: true,
            adminPrimerNombre: "Claudia",
            adminSegundoNombre: "Patricia",
            adminPrimerApellido: "Arango",
            adminSegundoApellido: "Gómez",
            adminCorreo: "carango@cendoj.ramajudicial.gov.co",
            jurisdiccion: "ORDINARIA",
            tipodespacho: "JUZGADO MUNICIPAL",
            deptomunicipio: "MANIZALES",
            consejoseccional: "CALDAS",
            distrito: "MANIZALES",
            circuito: "MANIZALES",
            especialidad: "LABORAL",
            tipo: "Permanente",
            codigoDespacho: "170014105002",
            nombreDespacho: "JUZGADO 002 LABORAL MUNICIPAL DE MANIZALES"
        },
        {
            id: 5,
            radicado: "SOL-2026-2811",
            fechaSolicitud: "2026-06-15",
            estado: "Aprobado",
            fechaRespuesta: "2026-06-16",
            notificado: false,
            adminPrimerNombre: "Hernán",
            adminSegundoNombre: "",
            adminPrimerApellido: "Cárdenas",
            adminSegundoApellido: "Mejía",
            adminCorreo: "hcardenas@cendoj.ramajudicial.gov.co",
            jurisdiccion: "ORDINARIA",
            tipodespacho: "JUZGADO DE CIRCUITO",
            deptomunicipio: "MANIZALES",
            consejoseccional: "CALDAS",
            distrito: "MANIZALES",
            circuito: "MANIZALES",
            especialidad: "LABORAL",
            tipo: "Permanente",
            codigoDespacho: "170013105003",
            nombreDespacho: "JUZGADO 003 LABORAL DEL CIRCUITO DE MANIZALES"
        },
        {
            id: 6,
            radicado: "SOL-2026-2755",
            fechaSolicitud: "2026-05-02",
            estado: "Rechazado",
            fechaRespuesta: "2026-05-06",
            notificado: true,
            motivoRechazo: "El código del despacho no corresponde al despacho indicado.",
            adminPrimerNombre: "Jaime",
            adminSegundoNombre: "Alberto",
            adminPrimerApellido: "Ruiz",
            adminSegundoApellido: "Parra",
            adminCorreo: "jruiz@cendoj.ramajudicial.gov.co",
            jurisdiccion: "ORDINARIA",
            tipodespacho: "JUZGADO MUNICIPAL",
            deptomunicipio: "IBAGUÉ",
            consejoseccional: "TOLIMA",
            distrito: "IBAGUÉ",
            circuito: "IBAGUÉ",
            especialidad: "CIVIL",
            tipo: "Permanente",
            codigoDespacho: "7300140030",
            nombreDespacho: "JUZGADO 004 CIVIL MUNICIPAL DE IBAGUÉ"
        }
    ]
};